using DbSqlLikeMem.Oracle.NHibernate;

namespace DbSqlLikeMem.Oracle.Test;

/// <summary>
/// Runs smoke tests for NHibernate integration using the Oracle in-memory mock provider.
/// Executa testes de fumaça para integração do NHibernate usando o provedor simulado em memória do Oracle.
/// </summary>
public sealed class NHibernateSmokeTests : NHibernateSupportTestsBase
{
    /// <summary>
    /// Gets the NHibernate dialect class used to emulate Oracle SQL behavior.
    /// Obtém a classe de dialeto do NHibernate usada para emular o comportamento SQL do Oracle.
    /// </summary>
    protected override string NhDialectClass => "NHibernate.Dialect.Oracle10gDialect, NHibernate";

    /// <summary>
    /// Gets the NHibernate driver class that connects NHibernate to the Oracle mock connection.
    /// Obtém a classe de driver do NHibernate que conecta o NHibernate à conexão simulada de Oracle.
    /// </summary>
    protected override string NhDriverClass => typeof(OracleNhMockDriver).AssemblyQualifiedName!;

    /// <summary>
    /// Enables in-memory pagination fallback for Oracle mocked pagination SQL generated by NHibernate.
    /// Habilita fallback de paginação em memória para SQL de paginação Oracle gerado pelo NHibernate em modo simulado.
    /// </summary>
    protected override bool UseInMemoryPaginationFallback => true;

    /// <summary>
    /// Creates and opens a Oracle mock connection for NHibernate smoke test execution.
    /// Cria e abre uma conexão simulada de Oracle para execução dos testes de fumaça do NHibernate.
    /// </summary>
    protected override DbConnection CreateOpenConnection()
    {
        var connection = new OracleConnectionMock([]);
        connection.Open();
        return connection;
    }
}
