using DbSqlLikeMem;
using DbSqlLikeMem.Models;

namespace DbSqlLikeMem.MySql;

internal partial class MySqlDialect
{
    partial void RegisterScalarFunctions(int version)
    {
        SqlSharedScalarFunctionRegistry.Register(this);

        var body = SqlFunctionBodyFactory.Identity();

        this.AddScalarFunction("IFNULL", "VARCHAR", body);
        this.AddScalarFunction("DATABASE", "VARCHAR", body);
        this.AddScalarFunction("SCHEMA", "VARCHAR", body);
        this.AddScalarFunction("CONNECTION_ID", "BIGINT", body);
        this.AddScalarFunction("VERSION", "VARCHAR", body);
        this.AddScalarFunction("CHARSET", "VARCHAR", body);
        this.AddScalarFunction("COLLATION", "VARCHAR", body);
        this.AddScalarFunction("CURRENT_USER", "VARCHAR", body, SqlScalarFunctionUsageKind.CallOrIdentifier, null);
        this.AddScalarFunction("SESSION_USER", "VARCHAR", body, SqlScalarFunctionUsageKind.CallOrIdentifier, null);
        this.AddScalarFunction("USER", "VARCHAR", body, SqlScalarFunctionUsageKind.CallOrIdentifier, null);
        this.AddScalarFunction("SYSTEM_USER", "VARCHAR", body, SqlScalarFunctionUsageKind.CallOrIdentifier, null);
        this.AddScalarFunction("FOUND_ROWS", "BIGINT", body);
        this.AddScalarFunction("ROW_COUNT", "BIGINT", body);
        this.AddScalarFunction("LAST_INSERT_ID", "BIGINT", body);
        this.AddScalarFunction("UUID_SHORT", "BIGINT", body);
        this.AddScalarFunction("GROUP_CONCAT", "VARCHAR", body, SqlScalarFunctionUsageKind.Call, null);

        this.AddScalarFunction("CURDATE", "DATE", body, SqlScalarFunctionUsageKind.Call, SqlTemporalFunctionKind.Date);
        this.AddScalarFunction("CURTIME", "TIME", body, SqlScalarFunctionUsageKind.Call, SqlTemporalFunctionKind.Time);
        this.AddScalarFunction("CURRENT_DATE", "DATE", body, SqlScalarFunctionUsageKind.Identifier, SqlTemporalFunctionKind.Date);
        this.AddScalarFunction("CURRENT_TIME", "TIME", body, SqlScalarFunctionUsageKind.Identifier, SqlTemporalFunctionKind.Time);
        this.AddScalarFunction("CURRENT_TIMESTAMP", "DATETIME", body, SqlScalarFunctionUsageKind.Identifier, SqlTemporalFunctionKind.DateTime);
        this.AddScalarFunction("LOCALTIME", "TIME", body, SqlScalarFunctionUsageKind.CallOrIdentifier, SqlTemporalFunctionKind.Time);
        this.AddScalarFunction("LOCALTIMESTAMP", "DATETIME", body, SqlScalarFunctionUsageKind.CallOrIdentifier, SqlTemporalFunctionKind.DateTime);
        this.AddScalarFunction("NOW", "DATETIME", body, SqlScalarFunctionUsageKind.Call, SqlTemporalFunctionKind.DateTime);
        this.AddScalarFunction("SYSDATE", "DATETIME", body, SqlScalarFunctionUsageKind.Call, SqlTemporalFunctionKind.DateTime);
        this.AddScalarFunction("SYSTEMDATE", "DATETIME", body, SqlScalarFunctionUsageKind.Identifier, SqlTemporalFunctionKind.DateTime);
        this.AddScalarFunction("UTC_DATE", "DATE", body, SqlScalarFunctionUsageKind.Call, SqlTemporalFunctionKind.Date);
        this.AddScalarFunction("UTC_TIME", "TIME", body, SqlScalarFunctionUsageKind.Call, SqlTemporalFunctionKind.Time);
        this.AddScalarFunction("UTC_TIMESTAMP", "DATETIME", body, SqlScalarFunctionUsageKind.Call, SqlTemporalFunctionKind.DateTime);

        this.AddScalarFunction("DATE", "DATE", body);
        this.AddScalarFunction("TIME", "TIME", body);
        this.AddScalarFunction("TIMESTAMP", "DATETIME", body);
        this.AddScalarFunction("CHAR_LENGTH", "BIGINT", body);
        this.AddScalarFunction("CHARACTER_LENGTH", "BIGINT", body);
        this.AddScalarFunction("BIT_LENGTH", "INT", body);
        this.AddScalarFunction("BIT_COUNT", "INT", body);
        this.AddScalarFunction("BIN", "VARCHAR", body);
        this.AddScalarFunction("CRC32", "BIGINT", body);
        this.AddScalarFunction("CONVERT", "VARCHAR", body);
        this.AddScalarFunction("CONV", "VARCHAR", body);
        this.AddScalarFunction("CONVERT_TZ", "DATETIME", body);
        this.AddScalarFunction("DATE_SUB", "DATETIME", body);
        this.AddScalarFunction("ELT", "VARCHAR", body);
        this.AddScalarFunction("EXPORT_SET", "VARCHAR", body);
        this.AddScalarFunction("FIND_IN_SET", "INT", body);
        this.AddScalarFunction("FROM_BASE64", "VARBINARY", body);
        this.AddScalarFunction("TO_BASE64", "VARCHAR", body);
        this.AddScalarFunction("FROM_DAYS", "DATE", body);
        this.AddScalarFunction("GET_FORMAT", "VARCHAR", body);
        this.AddScalarFunction("INET_ATON", "BIGINT", body);
        this.AddScalarFunction("INET_NTOA", "VARCHAR", body);
        this.AddScalarFunction("INET6_ATON", "VARBINARY", body);
        this.AddScalarFunction("INET6_NTOA", "VARCHAR", body);
        this.AddScalarFunction("IS_IPV4", "INT", body);
        this.AddScalarFunction("IS_IPV4_COMPAT", "INT", body);
        this.AddScalarFunction("IS_IPV4_MAPPED", "INT", body);
        this.AddScalarFunction("IS_IPV6", "INT", body);
        this.AddScalarFunction("AES_ENCRYPT", "VARBINARY", body);
        this.AddScalarFunction("AES_DECRYPT", "VARCHAR", body);
        this.AddScalarFunction("DES_ENCRYPT", "VARBINARY", body);
        this.AddScalarFunction("DES_DECRYPT", "VARCHAR", body);
        this.AddScalarFunction("ENCODE", "VARBINARY", body);
        this.AddScalarFunction("DECODE", "VARCHAR", body);
        this.AddScalarFunction("ENCRYPT", "VARCHAR", body);
        this.AddScalarFunction("DEFAULT", "VARCHAR", body);
        this.AddScalarFunction("MEMBER_OF", "BOOLEAN", body);
        this.AddScalarFunction("EXTRACTVALUE", "VARCHAR", body);
        this.AddScalarFunction("UPDATEXML", "VARCHAR", body);
        this.AddScalarFunction("LOG2", "DOUBLE", body);
        this.AddScalarFunction("MAKE_SET", "VARCHAR", body);
        this.AddScalarFunction("OCT", "VARCHAR", body);
        this.AddScalarFunction("ORD", "INT", body);
        this.AddScalarFunction("GREATEST", "VARCHAR", body, SqlScalarFunctionUsageKind.CallOrIdentifier, null);
        this.AddScalarFunction("LEAST", "VARCHAR", body, SqlScalarFunctionUsageKind.CallOrIdentifier, null);
        this.AddScalarFunction("POSITION", "INT", body);
        this.AddScalarFunction("RPAD", "VARCHAR", body);
        this.AddScalarFunction("SLEEP", "INT", body);
        this.AddScalarFunction("SUBSTRING_INDEX", "VARCHAR", body);
        this.AddScalarFunction("OCTET_LENGTH", "INT", body);
        this.AddScalarFunction("COMPRESS", "VARBINARY", body);
        this.AddScalarFunction("UNCOMPRESS", "VARBINARY", body);
        this.AddScalarFunction("CONVERT_TZ", "DATETIME", body);
        this.AddScalarFunction("TRUNCATE", "DECIMAL", body);
        this.AddScalarFunction("UNIX_TIMESTAMP", "BIGINT", body);
        this.AddScalarFunction("SHA", "VARCHAR", body);
        this.AddScalarFunction("SHA1", "VARCHAR", body);
        this.AddScalarFunction("SHA2", "VARCHAR", body);
        this.AddScalarFunction("UNCOMPRESSED_LENGTH", "BIGINT", body);
        this.AddScalarFunctionIf(version >= MySqlDialect.JsonExtractMinVersion, "JSON_EXTRACT", "VARCHAR", body);
        this.AddScalarFunctionIf(version >= MySqlDialect.JsonExtractMinVersion, "JSON_UNQUOTE", "VARCHAR", body);
        this.AddScalarFunctionIf(version >= MySqlDialect.JsonExtractMinVersion, "JSON_DEPTH", "INT", body);
        this.AddScalarFunctionIf(version >= MySqlDialect.JsonExtractMinVersion, "JSON_VALID", "INT", body);
        this.AddScalarFunctionIf(version >= MySqlDialect.JsonExtractMinVersion, "JSON_TYPE", "VARCHAR", body);
        this.AddScalarFunctionIf(version >= MySqlDialect.JsonExtractMinVersion, "JSON_LENGTH", "INT", body);
        this.AddScalarFunctionIf(version >= MySqlDialect.JsonExtractMinVersion, "JSON_ARRAY", "VARCHAR", body);
        this.AddScalarFunctionIf(version >= MySqlDialect.JsonExtractMinVersion, "JSON_OBJECT", "VARCHAR", body);
        this.AddScalarFunctionIf(version >= MySqlDialect.JsonExtractMinVersion, "JSON_QUOTE", "VARCHAR", body);
        this.AddScalarFunctionIf(version >= MySqlDialect.JsonExtractMinVersion, "JSON_PRETTY", "VARCHAR", body);
        this.AddScalarFunctionIf(version >= MySqlDialect.JsonExtractMinVersion, "JSON_KEYS", "VARCHAR", body);
        this.AddScalarFunctionIf(version >= MySqlDialect.JsonExtractMinVersion, "JSON_SET", "VARCHAR", body);
        this.AddScalarFunctionIf(version >= MySqlDialect.JsonExtractMinVersion, "JSON_REMOVE", "VARCHAR", body);
        this.AddScalarFunctionIf(version >= MySqlDialect.JsonExtractMinVersion, "JSON_CONTAINS", "INT", body);
        this.AddScalarFunctionIf(version >= MySqlDialect.JsonExtractMinVersion, "JSON_CONTAINS_PATH", "INT", body);
        this.AddScalarFunctionIf(version >= MySqlDialect.JsonExtractMinVersion, "JSON_SEARCH", "VARCHAR", body);
        this.AddScalarFunctionIf(version >= MySqlDialect.JsonExtractMinVersion, "JSON_INSERT", "VARCHAR", body);
        this.AddScalarFunctionIf(version >= MySqlDialect.JsonExtractMinVersion, "JSON_REPLACE", "VARCHAR", body);
        this.AddScalarFunction("DATE_ADD", "DATETIME", body);
        this.AddScalarFunction("ADDDATE", "DATETIME", body);
        this.AddScalarFunction("ADDTIME", "DATETIME", body);
        this.AddScalarFunction("TIMESTAMPADD", "DATETIME", body);
        this.AddScalarFunction("TRY_CAST", "VARCHAR", body);
        this.AddScalarFunction("DATEDIFF", "INT", body);
        this.AddScalarFunction("TIMESTAMPDIFF", "INT", body);
        this.AddScalarFunction("DAY", "INT", body);
        this.AddScalarFunction("MONTH", "INT", body);
        this.AddScalarFunction("YEAR", "INT", body);
        this.AddScalarFunction("QUARTER", "INT", body);
        this.AddScalarFunction("WEEK", "INT", body);
        this.AddScalarFunction("HOUR", "INT", body);
        this.AddScalarFunction("MINUTE", "INT", body);
        this.AddScalarFunction("SECOND", "INT", body);
        this.AddScalarFunction("MAKEDATE", "DATE", body);
        this.AddScalarFunction("MAKETIME", "TIME", body);
        this.AddScalarFunction("MICROSECOND", "INT", body);
        this.AddScalarFunction("MONTHNAME", "VARCHAR", body);
        this.AddScalarFunction("PERIOD_ADD", "INT", body);
        this.AddScalarFunction("PERIOD_DIFF", "INT", body);
        this.AddScalarFunction("SEC_TO_TIME", "TIME", body);
        this.AddScalarFunction("TIME_TO_SEC", "INT", body);
        this.AddScalarFunction("TO_DAYS", "INT", body);
        this.AddScalarFunction("TO_SECONDS", "BIGINT", body);
        this.AddScalarFunction("SUBDATE", "DATETIME", body);
        this.AddScalarFunction("SUBTIME", "DATETIME", body);
        this.AddScalarFunction("LAST_DAY", "DATE", body);
        this.AddScalarFunction("TIME_FORMAT", "VARCHAR", body);
        this.AddScalarFunction("TIMEDIFF", "TIME", body);
        this.AddScalarFunction("DATE_FORMAT", "VARCHAR", body);
        this.AddScalarFunction("STR_TO_DATE", "DATETIME", body);
        this.AddScalarFunction("FROM_UNIXTIME", "DATETIME", body);
        this.AddScalarFunction("DAYNAME", "VARCHAR", body);
        this.AddScalarFunction("DAYOFMONTH", "INT", body);
        this.AddScalarFunction("DAYOFWEEK", "INT", body);
        this.AddScalarFunction("DAYOFYEAR", "INT", body);
        this.AddScalarFunction("WEEKDAY", "INT", body);
        this.AddScalarFunction("WEEKOFYEAR", "INT", body);
        this.AddScalarFunction("YEARWEEK", "INT", body);
        this.AddScalarFunction("ANY_VALUE", "VARCHAR", body, SqlScalarFunctionUsageKind.Call, null);
        this.AddScalarFunction("BIT_AND", "BIGINT", body, SqlScalarFunctionUsageKind.Call, null);
        this.AddScalarFunction("BIT_OR", "BIGINT", body, SqlScalarFunctionUsageKind.Call, null);
        this.AddScalarFunction("BIT_XOR", "BIGINT", body, SqlScalarFunctionUsageKind.Call, null);
        this.AddScalarFunction("STD", "DOUBLE", body, SqlScalarFunctionUsageKind.Call, null);
        this.AddScalarFunction("STDDEV", "DOUBLE", body, SqlScalarFunctionUsageKind.Call, null);
        this.AddScalarFunction("STDDEV_POP", "DOUBLE", body, SqlScalarFunctionUsageKind.Call, null);
        this.AddScalarFunction("STDDEV_SAMP", "DOUBLE", body, SqlScalarFunctionUsageKind.Call, null);
        this.AddScalarFunction("VAR_POP", "DOUBLE", body, SqlScalarFunctionUsageKind.Call, null);
        this.AddScalarFunction("VAR_SAMP", "DOUBLE", body, SqlScalarFunctionUsageKind.Call, null);
        this.AddScalarFunction("VARIANCE", "DOUBLE", body, SqlScalarFunctionUsageKind.Call, null);
        this.AddScalarFunctionIf(version >= 56, "JSON_ARRAYAGG", "VARCHAR", body, SqlScalarFunctionUsageKind.Call, null);
        this.AddScalarFunctionIf(version >= 56, "JSON_OBJECTAGG", "VARCHAR", body, SqlScalarFunctionUsageKind.Call, null);

        this.AddScalarFunctionIf(version >= 56, "RANDOM_BYTES", "VARBINARY", body);
        this.AddScalarFunctionIf(version >= 56 && version < 80, "JSON_APPEND", "VARCHAR", body);
        this.AddScalarFunctionIf(version >= 56, "JSON_ARRAY_APPEND", "VARCHAR", body);
        this.AddScalarFunctionIf(version >= 56, "JSON_ARRAY_INSERT", "VARCHAR", body);
        this.AddScalarFunctionIf(version >= 56, "JSON_MERGE", "VARCHAR", body);
        this.AddScalarFunctionIf(version >= 56, "JSON_MERGE_PRESERVE", "VARCHAR", body);
        this.AddScalarFunctionIf(version >= 56, "JSON_MERGE_PATCH", "VARCHAR", body);
        this.AddScalarFunctionIf(version >= 80, "FORMAT_BYTES", "VARCHAR", body);
        this.AddScalarFunctionIf(version >= 80, "FORMAT_PICO_TIME", "VARCHAR", body);
        this.AddScalarFunctionIf(version >= 80, "JSON_STORAGE_SIZE", "BIGINT", body);
        this.AddScalarFunctionIf(version >= 80, "JSON_OVERLAPS", "INT", body);
        this.AddScalarFunctionIf(version >= 80, "UUID_TO_BIN", "VARBINARY", body);
        this.AddScalarFunctionIf(version >= 80, "BIN_TO_UUID", "VARCHAR", body);
        this.AddScalarFunctionIf(version >= 80, "IS_UUID", "INT", body);
    }
}
