using System.Diagnostics.CodeAnalysis;

namespace DbSqlLikeMem;

/// <summary>
/// EN: In-memory mock connection with table support, transactions, and simulated latency.
/// PT: Conexão simulado em memória com suporte a tabelas, transações e latência simulada.
/// </summary>
public abstract class DbConnectionMockBase(
    DbMock db,
    string? defaultDatabase = null
    ) : DbConnection
{
    private enum TransactionJournalEntryKind
    {
        Insert,
        Update,
        Delete,
        CreateTable,
        DropTable,
        CreateIndex,
        DropIndex,
        UpsertView,
        DropView,
        CreateSequence,
        DropSequence,
        UpdateSequence,
        UpsertFunction,
        DropFunction,
        UpsertProcedure
    }

    private enum TransactionTableRegistrationKind
    {
        Schema,
        ConnectionTemporary,
        GlobalTemporary
    }

    private sealed class TableReferenceComparer : IEqualityComparer<ITableMock>
    {
        public static readonly TableReferenceComparer Instance = new();

        public bool Equals(ITableMock? x, ITableMock? y) => ReferenceEquals(x, y);

        public int GetHashCode(ITableMock obj)
            => System.Runtime.CompilerServices.RuntimeHelpers.GetHashCode(obj);
    }

    private sealed record TransactionJournalEntry(
        TableMock Table,
        TransactionJournalEntryKind Kind,
        int RowIndex,
        Dictionary<int, object?>? Row,
        Dictionary<int, object?>? OldRowSnapshot,
        int PreviousNextIdentity,
        TransactionTableRegistrationKind RegistrationKind,
        string RegistrationKey,
        Idx? IndexDefinition = null,
        TransactionViewState? ViewState = null,
        TransactionSequenceState? SequenceState = null,
        TransactionFunctionState? FunctionState = null,
        TransactionProcedureState? ProcedureState = null);

    private sealed record TransactionViewState(
        string SchemaName,
        string ViewName,
        SqlSelectQuery? PreviousDefinition);

    private sealed record TransactionSequenceState(
        string SchemaName,
        string SequenceName,
        SequenceDef? PreviousDefinition,
        bool HadSessionValue,
        long SessionValue);

    private sealed record TransactionFunctionState(
        string SchemaName,
        string FunctionName,
        ScalarFunctionDef? PreviousDefinition);

    private sealed record TransactionProcedureState(
        string SchemaName,
        string ProcedureName,
        ProcedureDef? PreviousDefinition);

    private bool _disposed;
    private readonly Dictionary<string, int> _savepoints =
        new(StringComparer.OrdinalIgnoreCase);
    private readonly List<string> _savepointOrder = [];
    private readonly List<TransactionJournalEntry> _transactionJournal = [];
    private readonly HashSet<TableMock> _journalObservedTables = [];
    private int _transactionBeginJournalPosition;
    private bool _isReplayingTransactionJournal;

    /// <summary>
    /// EN: In-memory database associated with this connection.
    /// PT: Banco em memória associado a esta conexão.
    /// </summary>
    public DbMock Db { get; } = db;

    /// <summary>
    /// EN: Connection usage and performance metrics.
    /// PT: Métricas de uso e desempenho da conexão.
    /// </summary>
    public DbMetrics Metrics { get; } = new();

    /// <summary>
    /// EN: Enables or disables execution-plan capture for this connection by delegating to the underlying database.
    /// PT: Habilita ou desabilita a captura de planos de execução nesta conexão delegando para o banco subjacente.
    /// </summary>
    public bool CaptureExecutionPlans
    {
        get => Db.CaptureExecutionPlans;
        set => Db.CaptureExecutionPlans = value;
    }

    /// <summary>
    /// EN: Controls whether affected-row snapshots should be captured for diagnostics.
    /// PT: Controla se snapshots de linhas afetadas devem ser capturados para diagnóstico.
    /// </summary>
    public bool CaptureAffectedRowSnapshots { get; set; } = true;

    /// <summary>
    /// EN: Last execution plan generated by this connection.
    /// PT: Último plano de execução gerado por esta conexão.
    /// </summary>
    public string? LastExecutionPlan { get; private set; }

    /// <summary>
    /// EN: Execution plans generated during the last command execution.
    /// PT: Planos de execução gerados durante a última execução de comando.
    /// </summary>
    public IReadOnlyList<string> LastExecutionPlans => _lastExecutionPlans;

    private readonly List<string> _lastExecutionPlans = [];
    private readonly System.Collections.Concurrent.ConcurrentDictionary<string, SelectPlan> _selectPlanCache = new(StringComparer.Ordinal);
    private readonly List<QueryDebugTrace> _lastDebugTraces = [];
    private int _debugTraceCaptureDepth;
    private int _selectPlanCacheGeneration;
    private long _lastFoundRows;
    private object? _lastInsertId;
    private readonly AutoSqlDialect _autoSqlDialect = new();
    private readonly Dictionary<string, long> _sessionSequenceValues =
        new(StringComparer.OrdinalIgnoreCase);
    private readonly Dictionary<string, object?> _sessionContextValues =
        new(StringComparer.OrdinalIgnoreCase);
    private byte[]? _contextInfo;
    private string? _lastSessionSequenceKey;
    private string? _currentQueryText;

    internal void ClearExecutionPlans()
    {
        LastExecutionPlan = null;
        _lastExecutionPlans.Clear();
        ClearDebugTraces();
    }

    internal void ClearSelectPlanCache()
    {
        _selectPlanCache.Clear();
        _selectPlanCacheGeneration++;
    }

    internal int GetSelectPlanCacheGeneration()
        => _selectPlanCacheGeneration;

    internal bool TryGetCachedSelectPlan(
        string cacheKey,
        out SelectPlan? plan)
        => _selectPlanCache.TryGetValue(cacheKey, out plan);

    internal void TryCacheSelectPlan(string cacheKey, SelectPlan plan)
        => _selectPlanCache.TryAdd(cacheKey, plan);

    internal void RegisterExecutionPlan(string executionPlan)
    {
        if (!Db.CaptureExecutionPlans || string.IsNullOrWhiteSpace(executionPlan))
            return;

        LastExecutionPlan = executionPlan;
        _lastExecutionPlans.Add(executionPlan);
    }

    internal string? GetCurrentQueryText()
        => _currentQueryText;

    internal IDisposable BeginCurrentQueryScope(string? sql)
        => new CurrentQueryScope(this, sql);

    /// <summary>
    /// EN: Last runtime query debug trace captured for this connection.
    /// PT: Ultimo trace de debug de query em runtime capturado para esta conexao.
    /// </summary>
    public QueryDebugTrace? LastDebugTrace { get; private set; }

    /// <summary>
    /// EN: Runtime query debug traces captured during the last command execution.
    /// PT: Traces de debug de query em runtime capturados durante a ultima execucao de comando.
    /// </summary>
    public IReadOnlyList<QueryDebugTrace> LastDebugTraces => _lastDebugTraces;

    /// <summary>
    /// EN: Enables automatic SQL dialect compatibility mode for parsing and execution on this connection.
    /// PT: Habilita o modo automatico de compatibilidade de dialeto SQL para parsing e execucao nesta conexao.
    /// </summary>
    public bool UseAutoSqlDialect { get; set; }

    /// <summary>
    /// EN: Maximum number of runtime debug traces retained in connection history.
    /// PT: Numero maximo de traces de debug em runtime retidos no historico da conexao.
    /// </summary>
    public int DebugTraceRetentionLimit { get; set; } = int.MaxValue;

    /// <summary>
    /// EN: Clears the runtime debug trace history kept by this connection.
    /// PT: Limpa o historico de traces de debug em runtime mantido por esta conexao.
    /// </summary>
    public void ClearDebugTraces()
    {
        LastDebugTrace = null;
        _lastDebugTraces.Clear();
    }

    /// <summary>
    /// EN: Wraps this mock connection with the ADO.NET interception pipeline.
    /// PT: Encapsula esta conexao mock com o pipeline de interceptacao ADO.NET.
    /// </summary>
    /// <param name="interceptors">EN: Interceptors applied in registration order. PT: Interceptors aplicados na ordem de registro.</param>
    /// <returns>EN: Wrapped connection. PT: Conexao encapsulada.</returns>
    public DbConnection Intercept(params DbConnectionInterceptor[] interceptors)
        => DbInterceptionPipeline.Wrap(this, interceptors);

    internal bool IsDebugTraceCaptureEnabled => _debugTraceCaptureDepth > 0;

    internal ISqlDialect ExecutionDialect => UseAutoSqlDialect ? _autoSqlDialect : Db.Dialect;

    internal IDisposable BeginDebugTraceCapture()
    {
        if (_debugTraceCaptureDepth == 0)
            ClearDebugTraces();

        _debugTraceCaptureDepth++;
        return new DebugTraceCaptureScope(this);
    }

    internal void RegisterDebugTrace(QueryDebugTrace trace)
    {
        ArgumentNullExceptionCompatible.ThrowIfNull(trace, nameof(trace));
        LastDebugTrace = trace;
        _lastDebugTraces.Add(trace);
        TrimDebugTraceHistoryIfNeeded();
    }

    internal void RestoreDebugTraces(IReadOnlyList<QueryDebugTrace> traces)
    {
        ArgumentNullExceptionCompatible.ThrowIfNull(traces, nameof(traces));
        _lastDebugTraces.Clear();
        _lastDebugTraces.AddRange(traces);
        TrimDebugTraceHistoryIfNeeded();
        LastDebugTrace = _lastDebugTraces.Count > 0 ? _lastDebugTraces[^1] : null;
    }

    /// <summary>
    /// EN: Executes a SQL command and returns the captured runtime operator traces for the reader statements in that execution.
    /// PT: Executa um comando SQL e retorna os traces de operadores em runtime capturados para os statements de leitura dessa execucao.
    /// </summary>
    /// <param name="sql">EN: SQL text to execute. PT: Texto SQL a executar.</param>
    /// <returns>EN: Captured runtime traces for the executed command. PT: Traces de runtime capturados para o comando executado.</returns>
    public IReadOnlyList<QueryDebugTrace> DebugSqlBatch(string sql)
    {
        ArgumentExceptionCompatible.ThrowIfNullOrWhiteSpace(sql, nameof(sql));

        var shouldOpen = State != ConnectionState.Open;
        List<QueryDebugTrace>? retainedTraces = null;
        if (shouldOpen)
            Open();

        try
        {
            using var scope = BeginDebugTraceCapture();
            using var command = CreateCommand();
            command.CommandText = sql;
            using var reader = command.ExecuteReader();

            do
            {
                while (reader.Read())
                {
                }
            }
            while (reader.NextResult());

            if (_lastDebugTraces.Count == 0)
                throw new InvalidOperationException("No runtime debug trace was captured for the executed SQL.");

            ContextualizeDebugTraces(sql);
            return _lastDebugTraces.AsReadOnly();
        }
        finally
        {
            if (shouldOpen && LastDebugTrace is not null)
                retainedTraces = [.. _lastDebugTraces];

            if (shouldOpen && State == ConnectionState.Open)
                Close();

            if (retainedTraces is not null)
                RestoreDebugTraces(retainedTraces);
        }
    }

    /// <summary>
    /// EN: Executes a SQL command and returns the captured runtime operator trace for the last reader query.
    /// PT: Executa um comando SQL e retorna o trace de operadores em runtime capturado para a ultima query de leitura.
    /// </summary>
    /// <param name="sql">EN: SQL text to execute. PT: Texto SQL a executar.</param>
    /// <returns>EN: Captured runtime trace for the executed command. PT: Trace de runtime capturado para o comando executado.</returns>
    public QueryDebugTrace DebugSql(string sql)
        => DebugSqlBatch(sql).Last();

    /// <summary>
    /// EN: Executes a SQL command and returns the formatted runtime trace for the last reader query.
    /// PT: Executa um comando SQL e retorna o trace de runtime formatado para a ultima query de leitura.
    /// </summary>
    /// <param name="sql">EN: SQL text to execute. PT: Texto SQL a executar.</param>
    /// <returns>EN: Formatted runtime trace. PT: Trace de runtime formatado.</returns>
    public string DebugSqlText(string sql)
        => QueryDebugTraceFormatter.Format(DebugSql(sql));

    /// <summary>
    /// EN: Executes a SQL command and returns the formatted runtime traces for all reader statements in the batch.
    /// PT: Executa um comando SQL e retorna os traces de runtime formatados para todos os statements de leitura do lote.
    /// </summary>
    /// <param name="sql">EN: SQL text to execute. PT: Texto SQL a executar.</param>
    /// <returns>EN: Formatted runtime trace batch. PT: Lote formatado de traces de runtime.</returns>
    public string DebugSqlBatchText(string sql)
        => QueryDebugTraceFormatter.FormatBatch(DebugSqlBatch(sql));

    /// <summary>
    /// EN: Executes a SQL command and returns the runtime trace for the last reader query as structured JSON.
    /// PT: Executa um comando SQL e retorna o trace de runtime da ultima query de leitura como JSON estruturado.
    /// </summary>
    /// <param name="sql">EN: SQL text to execute. PT: Texto SQL a executar.</param>
    /// <returns>EN: JSON runtime trace. PT: Trace de runtime em JSON.</returns>
    public string DebugSqlJson(string sql)
        => QueryDebugTraceFormatter.FormatJson(DebugSql(sql));

    /// <summary>
    /// EN: Executes a SQL command and returns the runtime traces for all reader statements in the batch as structured JSON.
    /// PT: Executa um comando SQL e retorna os traces de runtime de todos os statements de leitura do lote como JSON estruturado.
    /// </summary>
    /// <param name="sql">EN: SQL text to execute. PT: Texto SQL a executar.</param>
    /// <returns>EN: JSON runtime trace batch. PT: Lote de traces de runtime em JSON.</returns>
    public string DebugSqlBatchJson(string sql)
        => QueryDebugTraceFormatter.FormatBatchJson(DebugSqlBatch(sql));

    /// <summary>
    /// EN: Returns a snapshot of the currently retained runtime debug traces without executing new SQL.
    /// PT: Retorna um snapshot dos traces de debug em runtime atualmente retidos sem executar novo SQL.
    /// </summary>
    /// <returns>EN: Snapshot of the retained runtime traces. PT: Snapshot dos traces de runtime retidos.</returns>
    public IReadOnlyList<QueryDebugTrace> GetDebugTraceSnapshot()
        => [.. _lastDebugTraces];

    /// <summary>
    /// EN: Returns the currently retained runtime debug traces formatted as text without executing new SQL.
    /// PT: Retorna os traces de debug em runtime atualmente retidos formatados como texto sem executar novo SQL.
    /// </summary>
    /// <returns>EN: Formatted runtime trace snapshot. PT: Snapshot formatado dos traces de runtime.</returns>
    public string GetDebugTraceSnapshotText()
        => QueryDebugTraceFormatter.FormatBatch(GetDebugTraceSnapshot());

    /// <summary>
    /// EN: Returns the currently retained runtime debug traces as JSON without executing new SQL.
    /// PT: Retorna os traces de debug em runtime atualmente retidos como JSON sem executar novo SQL.
    /// </summary>
    /// <returns>EN: JSON runtime trace snapshot. PT: Snapshot JSON dos traces de runtime.</returns>
    public string GetDebugTraceSnapshotJson()
        => QueryDebugTraceFormatter.FormatBatchJson(GetDebugTraceSnapshot());

    /// <summary>
    /// EN: Returns the last retained runtime debug trace without executing new SQL.
    /// PT: Retorna o ultimo trace de debug em runtime retido sem executar novo SQL.
    /// </summary>
    /// <returns>EN: Last retained runtime trace, when available. PT: Ultimo trace de runtime retido, quando disponivel.</returns>
    public QueryDebugTrace? GetLastDebugTraceSnapshot()
        => LastDebugTrace;

    /// <summary>
    /// EN: Tries to get the last retained runtime debug trace without throwing when none is available.
    /// PT: Tenta obter o ultimo trace de debug em runtime retido sem lancar excecao quando nenhum estiver disponivel.
    /// </summary>
    /// <param name="trace">EN: Last retained trace when available; otherwise null. PT: Ultimo trace retido quando disponivel; caso contrario, null.</param>
    /// <returns>EN: True when a retained trace exists; otherwise false. PT: True quando existe um trace retido; caso contrario, false.</returns>
    public bool TryGetLastDebugTraceSnapshot(
#if NET6_0_OR_GREATER
        [NotNullWhen(true)]
#endif
    out QueryDebugTrace? trace)
    {
        trace = LastDebugTrace;
        return trace is not null;
    }

    /// <summary>
    /// EN: Returns the last retained runtime debug trace formatted as text without executing new SQL.
    /// PT: Retorna o ultimo trace de debug em runtime retido formatado como texto sem executar novo SQL.
    /// </summary>
    /// <returns>EN: Formatted last runtime trace. PT: Ultimo trace de runtime formatado.</returns>
    public string GetLastDebugTraceSnapshotText()
    {
        if (LastDebugTrace is null)
            throw new InvalidOperationException("No runtime debug trace is currently retained.");

        return QueryDebugTraceFormatter.Format(LastDebugTrace);
    }

    /// <summary>
    /// EN: Returns the last retained runtime debug trace as JSON without executing new SQL.
    /// PT: Retorna o ultimo trace de debug em runtime retido como JSON sem executar novo SQL.
    /// </summary>
    /// <returns>EN: JSON payload for the last runtime trace. PT: Payload JSON do ultimo trace de runtime.</returns>
    public string GetLastDebugTraceSnapshotJson()
    {
        if (LastDebugTrace is null)
            throw new InvalidOperationException("No runtime debug trace is currently retained.");

        return QueryDebugTraceFormatter.FormatJson(LastDebugTrace);
    }

    /// <summary>
    /// EN: Exports the current structural schema snapshot of this connection database.
    /// PT: Exporta o snapshot estrutural atual do banco associado a esta conexao.
    /// </summary>
    /// <returns>EN: Exported schema snapshot. PT: Snapshot de schema exportado.</returns>
    public SchemaSnapshot ExportSchemaSnapshot()
        => SchemaSnapshot.Export(this);

    /// <summary>
    /// EN: Exports the current structural schema snapshot of this connection database as JSON.
    /// PT: Exporta o snapshot estrutural atual do banco associado a esta conexao como JSON.
    /// </summary>
    /// <returns>EN: Serialized schema snapshot JSON. PT: JSON serializado do snapshot de schema.</returns>
    public string ExportSchemaSnapshotJson()
        => ExportSchemaSnapshot().ToJson();

    /// <summary>
    /// EN: Returns the supported schema snapshot subset profile for this connection database.
    /// PT: Retorna o perfil do subset suportado de schema snapshot para o banco desta conexao.
    /// </summary>
    /// <returns>EN: Supported schema snapshot profile. PT: Perfil suportado de schema snapshot.</returns>
    public SchemaSnapshotSupportProfile GetSchemaSnapshotSupportProfile()
        => SchemaSnapshot.GetSupportProfile(this);

    /// <summary>
    /// EN: Returns the supported schema snapshot subset profile for this connection database as text.
    /// PT: Retorna o perfil do subset suportado de schema snapshot para o banco desta conexao como texto.
    /// </summary>
    /// <returns>EN: Multi-line support profile text. PT: Texto multilinha do perfil de suporte.</returns>
    public string GetSchemaSnapshotSupportProfileText()
        => GetSchemaSnapshotSupportProfile().ToText();

    /// <summary>
    /// EN: Exports the current structural schema snapshot of this connection database to a JSON file.
    /// PT: Exporta o snapshot estrutural atual do banco associado a esta conexao para um arquivo JSON.
    /// </summary>
    /// <param name="path">EN: Target JSON file path. PT: Caminho do arquivo JSON de destino.</param>
    public void ExportSchemaSnapshotToFile(string path)
        => ExportSchemaSnapshot().SaveToFile(path);

    /// <summary>
    /// EN: Imports a structural schema snapshot JSON into the database associated with this connection.
    /// PT: Importa um JSON de snapshot estrutural de schema para o banco associado a esta conexao.
    /// </summary>
    /// <param name="json">EN: Serialized schema snapshot. PT: Snapshot de schema serializado.</param>
    public void ImportSchemaSnapshot(string json)
        => ImportSchemaSnapshot(json, ensureCompatibility: false);

    /// <summary>
    /// EN: Imports a structural schema snapshot JSON into the database associated with this connection with optional compatibility validation.
    /// PT: Importa um JSON de snapshot estrutural de schema para o banco associado a esta conexao com validacao opcional de compatibilidade.
    /// </summary>
    /// <param name="json">EN: Serialized schema snapshot. PT: Snapshot de schema serializado.</param>
    /// <param name="ensureCompatibility">EN: True to enforce dialect/version compatibility before replay. PT: True para exigir compatibilidade de dialeto/versao antes do replay.</param>
    public void ImportSchemaSnapshot(
        string json,
        bool ensureCompatibility)
        => ImportSchemaSnapshotCore(SchemaSnapshot.Load(json), ensureCompatibility);

    /// <summary>
    /// EN: Imports a structural schema snapshot JSON file into the database associated with this connection.
    /// PT: Importa um arquivo JSON de snapshot estrutural de schema para o banco associado a esta conexao.
    /// </summary>
    /// <param name="path">EN: Source JSON file path. PT: Caminho do arquivo JSON de origem.</param>
    public void ImportSchemaSnapshotFromFile(string path)
        => ImportSchemaSnapshotFromFile(path, ensureCompatibility: false);

    /// <summary>
    /// EN: Imports a structural schema snapshot JSON file into the database associated with this connection with optional compatibility validation.
    /// PT: Importa um arquivo JSON de snapshot estrutural de schema para o banco associado a esta conexao com validacao opcional de compatibilidade.
    /// </summary>
    /// <param name="path">EN: Source JSON file path. PT: Caminho do arquivo JSON de origem.</param>
    /// <param name="ensureCompatibility">EN: True to enforce dialect/version compatibility before replay. PT: True para exigir compatibilidade de dialeto/versao antes do replay.</param>
    public void ImportSchemaSnapshotFromFile(
        string path,
        bool ensureCompatibility)
        => ImportSchemaSnapshotCore(SchemaSnapshot.LoadFromFile(path), ensureCompatibility);

    internal void ImportSchemaSnapshotCore(
        SchemaSnapshot snapshot,
        bool ensureCompatibility)
    {
        ArgumentNullExceptionCompatible.ThrowIfNull(snapshot, nameof(snapshot));
        if (ensureCompatibility)
            snapshot.EnsureCompatibleWith(Db);

        snapshot.ApplyTo(Db);
        AlignCurrentDatabaseToImportedSchemas(snapshot);
    }

    private void AlignCurrentDatabaseToImportedSchemas(SchemaSnapshot snapshot)
    {
        if (Db.TryGetValue(Database, out _))
            return;

        var nextDatabase = snapshot.Schemas
            .FirstOrDefault(static schema =>
                schema.Tables.Count > 0
                || schema.Views.Count > 0
                || schema.Procedures.Count > 0
                || schema.Sequences.Count > 0)
            ?.Name
            ?? snapshot.Schemas
            .Select(static schema => schema.Name)
            .FirstOrDefault(name => name.Equals("DefaultSchema", StringComparison.OrdinalIgnoreCase))
            ?? snapshot.Schemas.FirstOrDefault()?.Name
            ?? "DefaultSchema";

        ChangeDatabase(nextDatabase);
    }

    private void ContextualizeDebugTraces(string sql)
    {
        var statements = SqlQueryParser
            .SplitStatements(sql, ExecutionDialect)
            .Where(static statement => !string.IsNullOrWhiteSpace(statement))
            .Select(static statement => statement.Trim())
            .ToList();

        if (statements.Count == 0 || _lastDebugTraces.Count == 0)
            return;

        var contextualized = new List<QueryDebugTrace>(_lastDebugTraces.Count);
        var statementOffset = Math.Max(0, statements.Count - _lastDebugTraces.Count);
        for (var i = 0; i < _lastDebugTraces.Count; i++)
        {
            var statementIndex = statementOffset + i;
            var sqlText = statementIndex < statements.Count
                ? statements[statementIndex]
                : null;
            contextualized.Add(_lastDebugTraces[i].WithStatementContext(statementIndex, sqlText));
        }

        RestoreDebugTraces(contextualized);
    }

    private void TrimDebugTraceHistoryIfNeeded()
    {
        var retentionLimit = Math.Max(1, DebugTraceRetentionLimit);

        if (_lastDebugTraces.Count <= retentionLimit)
            return;

        var removeCount = _lastDebugTraces.Count - retentionLimit;
        _lastDebugTraces.RemoveRange(0, removeCount);
        LastDebugTrace = _lastDebugTraces[^1];
    }

    private sealed class DebugTraceCaptureScope(DbConnectionMockBase connection) : IDisposable
    {
        private DbConnectionMockBase? _connection = connection;

        public void Dispose()
        {
            if (_connection is null)
                return;

            _connection._debugTraceCaptureDepth = Math.Max(0, _connection._debugTraceCaptureDepth - 1);
            _connection = null;
        }
    }

    private sealed class CurrentQueryScope : IDisposable
    {
        private DbConnectionMockBase? _connection;
        private readonly string? _previousQueryText;

        public CurrentQueryScope(DbConnectionMockBase connection, string? sql)
        {
            _connection = connection;
            _previousQueryText = connection._currentQueryText;
            connection._currentQueryText = sql;
        }

        public void Dispose()
        {
            if (_connection is null)
                return;

            _connection._currentQueryText = _previousQueryText;
            _connection = null;
        }
    }

    internal void SetLastFoundRows(long value)
        => _lastFoundRows = Math.Max(0, value);

    internal long GetLastFoundRows()
        => _lastFoundRows;

    internal void SetLastInsertId(object? value)
        => _lastInsertId = value;

    internal object? GetLastInsertId()
        => _lastInsertId;

    /// <summary>
    /// EN: Simulated latency in milliseconds for each operation.
    /// PT: Latência simulada em milissegundos para cada operação.
    /// </summary>
    public int SimulatedLatencyMs { get; set; }
    /// <summary>
    /// EN: Probability of simulated network failure (0 to 1).
    /// PT: Probabilidade de falha simulada de rede (0 a 1).
    /// </summary>
    public double DropProbability { get; set; }

    /// <summary>
    /// EN: Simulated connection string.
    /// PT: String de conexão simulada.
    /// </summary>
    [AllowNull]
    public override string ConnectionString { get; set; } = "";

    /// <summary>
    /// EN: Simulated connection timeout.
    /// PT: Tempo limite de conexão simulada.
    /// </summary>
    public override int ConnectionTimeout { get; } = 1;

    private string _database = ResolveInitialDatabase(db, defaultDatabase);
    /// <summary>
    /// EN: Current database/schema name.
    /// PT: Nome do banco/schema atual.
    /// </summary>
    public override string Database => _database;

    private ConnectionState _state = ConnectionState.Closed;
    /// <summary>
    /// EN: Current connection state.
    /// PT: Estado atual da conexão.
    /// </summary>
    public override ConnectionState State => _state;

    private readonly string _dataSource = "";
    /// <summary>
    /// EN: Simulated data source.
    /// PT: Fonte de dados simulada.
    /// </summary>
    public override string DataSource => _dataSource;

    private static string ResolveInitialDatabase(DbMock db, string? defaultDatabase)
    {
        if (!string.IsNullOrWhiteSpace(defaultDatabase))
            return defaultDatabase!;

        if (db.TryGetValue("DefaultSchema", out _))
            return "DefaultSchema";

        return db.GetSchemaName(null);
    }

    /// <summary>
    /// EN: Backing field for the simulated server version.
    /// PT: Campo de suporte para a versão simulada do servidor.
    /// </summary>
    protected string _serverVersion = "";
    /// <summary>
    /// EN: Simulated server version.
    /// PT: Versão do servidor simulada.
    /// </summary>
    public override string ServerVersion => _serverVersion;

    /// <summary>
    /// EN: Current active transaction, if any.
    /// PT: Transação ativa atual, se houver.
    /// </summary>
    protected DbTransaction? CurrentTransaction { get; private set; }

    /// <summary>
    /// EN: Indicates whether there is an active transaction in this connection.
    /// PT: Indica se existe transação ativa nesta conexão.
    /// </summary>
    public bool HasActiveTransaction => CurrentTransaction != null;

    /// <summary>
    /// EN: Active transaction isolation level for the current connection.
    /// PT: Nível de isolamento ativo da transação atual da conexão.
    /// </summary>
    public IsolationLevel CurrentIsolationLevel { get; private set; } = IsolationLevel.Unspecified;

    /// <summary>
    /// EN: Indicates whether savepoints are supported by this provider.
    /// PT: Indica se savepoints são suportados por este provedor.
    /// </summary>
    protected virtual bool SupportsSavepoints => true;

    /// <summary>
    /// EN: Indicates whether release savepoint is supported by this provider.
    /// PT: Indica se RELEASE SAVEPOINT é suportado por este provedor.
    /// </summary>
    protected virtual bool SupportsReleaseSavepoint => true;

    private readonly Dictionary<string, ITableMock> _temporaryTables =
        new(StringComparer.OrdinalIgnoreCase);

    #region Table

    private string BuildTemporaryTableKey(
        string tableName,
        string? schemaName)
    {
        var schema = Db.GetSchemaName(schemaName ?? Database);
        return $"{schema}:{tableName.NormalizeName()}";
    }

    private IEnumerable<ITableMock> ListTemporaryTables(
        string? schemaName = null)
    {
        var schema = Db.GetSchemaName(schemaName ?? Database);
        var prefix = $"{schema}:";
        return _temporaryTables
            .Where(entry => entry.Key.StartsWith(prefix, StringComparison.OrdinalIgnoreCase))
            .Select(entry => entry.Value);
    }

    /// <summary>
    /// EN: Creates and adds a temporary table to the connection scope.
    /// PT: Cria e adiciona uma tabela temporária no escopo da conexão.
    /// </summary>
    /// <param name="tableName">EN: Table name. PT: Nome da tabela.</param>
    /// <param name="columns">EN: Table columns. PT: Colunas da tabela.</param>
    /// <param name="rows">EN: Initial rows. PT: Linhas iniciais.</param>
    /// <param name="schemaName">EN: Target schema. PT: Schema alvo.</param>
    /// <returns>EN: Created table. PT: Tabela criada.</returns>
    public ITableMock AddTemporaryTable(
        string tableName,
        IEnumerable<Col>? columns = null,
        IEnumerable<Dictionary<int, object?>>? rows = null,
        string? schemaName = null)
    {
        var schemaKey = Db.GetSchemaName(schemaName ?? Database);
        var key = BuildTemporaryTableKey(tableName, schemaKey);
        if (!Db.TryGetValue(schemaKey, out var schemaMock) || schemaMock == null)
            schemaMock = Db.CreateSchema(schemaKey);
        var schema = (SchemaMock)schemaMock;
        var materializedRows = rows as IReadOnlyList<Dictionary<int, object?>> ?? rows?.ToList();
        var table = schema.CreateTableInstance(
            tableName,
            columns ?? [],
            CurrentTransaction == null ? materializedRows : null);
        _temporaryTables.Add(key, table);
        if (CurrentTransaction != null)
        {
            AttachTransactionJournal(table);
            RecordCreatedTable((TableMock)table, TransactionTableRegistrationKind.ConnectionTemporary, key);
            if (materializedRows is { Count: > 0 })
            {
                table.AddRange(materializedRows.Select(
                    static row => row.ToDictionary(entry => entry.Key, entry => entry.Value)));
            }
        }
        ClearSelectPlanCache();
        return table;
    }

    internal ITableMock AddGlobalTemporaryTable(
        string tableName,
        IEnumerable<Col>? columns = null,
        IEnumerable<Dictionary<int, object?>>? rows = null,
        string? schemaName = null)
    {
        var materializedRows = rows as IReadOnlyList<Dictionary<int, object?>> ?? rows?.ToList();
        var table = Db.AddGlobalTemporaryTable(
            tableName,
            columns,
            CurrentTransaction == null ? materializedRows : null,
            schemaName);

        if (CurrentTransaction != null)
        {
            AttachTransactionJournal(table);
            RecordCreatedTable(
                (TableMock)table,
                TransactionTableRegistrationKind.GlobalTemporary,
                BuildTemporaryTableKey(tableName, schemaName));
            if (materializedRows is { Count: > 0 })
            {
                table.AddRange(materializedRows.Select(
                    static row => row.ToDictionary(entry => entry.Key, entry => entry.Value)));
            }
        }

        ClearSelectPlanCache();
        return table;
    }

    /// <summary>
    /// EN: Tries to get a temporary table by name.
    /// PT: Tenta obter uma tabela temporária pelo nome.
    /// </summary>
    /// <param name="tableName">EN: Table name. PT: Nome da tabela.</param>
    /// <param name="tb">EN: Found table, if any. PT: Tabela encontrada, se houver.</param>
    /// <param name="schemaName">EN: Target schema. PT: Schema alvo.</param>
    /// <returns>EN: True if it exists. PT: True se existir.</returns>
    public bool TryGetTemporaryTable(
        string tableName,
        out ITableMock? tb,
        string? schemaName = null)
        => _temporaryTables.TryGetValue(
            BuildTemporaryTableKey(tableName, schemaName),
            out tb);

    internal bool TryGetGlobalTemporaryTable(
        string tableName,
        out ITableMock? tb,
        string? schemaName = null)
        => Db.TryGetGlobalTemporaryTable(tableName, out tb, schemaName);

    /// <summary>
    /// EN: Creates and adds a table to the database.
    /// PT: Cria e adiciona uma tabela ao banco.
    /// </summary>
    /// <param name="tableName">EN: Table name. PT: Nome da tabela.</param>
    /// <param name="columns">EN: Table columns. PT: Colunas da tabela.</param>
    /// <param name="rows">EN: Initial rows. PT: Linhas iniciais.</param>
    /// <param name="schemaName">EN: Target schema. PT: Schema alvo.</param>
    /// <returns>EN: Created table. PT: Tabela criada.</returns>
    public ITableMock AddTable(
        string tableName,
        IEnumerable<Col>? columns = null,
        IEnumerable<Dictionary<int, object?>>? rows = null,
        string? schemaName = null)
    {
        var table = Db.AddTable(
            tableName,
            columns,
            rows,
            schemaName ?? Database);

        if (CurrentTransaction != null && table is TableMock tableMock)
        {
            AttachTransactionJournal(tableMock);
            RecordCreatedTable(
                tableMock,
                TransactionTableRegistrationKind.Schema,
                tableMock.TableName);
        }

        ClearSelectPlanCache();
        return table;
    }

    /// <summary>
    /// EN: Gets a table by name, throwing if it does not exist.
    /// PT: Obtém uma tabela pelo nome, lançando erro se não existir.
    /// </summary>
    /// <param name="tableName">EN: Table name. PT: Nome da tabela.</param>
    /// <param name="schemaName">EN: Target schema. PT: Schema alvo.</param>
    /// <returns>EN: Found table. PT: Tabela encontrada.</returns>
    public ITableMock GetTable(
        string tableName,
        string? schemaName = null)
    {
        if (TryGetTemporaryTable(tableName, out var tb, schemaName)
            && tb != null)
        {
            return tb;
        }

        if (TryGetGlobalTemporaryTable(tableName, out tb, schemaName)
            && tb != null)
        {
            return tb;
        }

        return Db.GetTable(
            tableName,
            schemaName ?? Database);
    }

    /// <summary>
    /// EN: Tries to get a table by name.
    /// PT: Tenta obter uma tabela pelo nome.
    /// </summary>
    /// <param name="tableName">EN: Table name. PT: Nome da tabela.</param>
    /// <param name="tb">EN: Found table, if any. PT: Tabela encontrada, se houver.</param>
    /// <param name="schemaName">EN: Target schema. PT: Schema alvo.</param>
    /// <returns>EN: True if it exists. PT: True se existir.</returns>
    public bool TryGetTable(
        string tableName,
        out ITableMock? tb,
        string? schemaName = null)
    {
        if (TryGetTemporaryTable(tableName, out tb, schemaName)
            && tb != null)
        {
            return true;
        }

        if (TryGetGlobalTemporaryTable(tableName, out tb, schemaName)
            && tb != null)
        {
            return true;
        }

        return Db.TryGetTable(
            tableName,
            out tb,
            schemaName ?? Database);
    }

    internal bool IsTemporaryTable(
        ITableMock table,
        string tableName,
        string? schemaName = null)
    {
        if (TryGetTemporaryTable(tableName, out var connectionTemp, schemaName)
            && connectionTemp != null
            && ReferenceEquals(connectionTemp, table))
            return true;

        if (TryGetGlobalTemporaryTable(tableName, out var globalTemp, schemaName)
            && globalTemp != null
            && ReferenceEquals(globalTemp, table))
            return true;

        return false;
    }

    private TransactionTableRegistrationKind GetRegistrationKind(TableMock table)
    {
        if (_temporaryTables.Values.Any(candidate => ReferenceEquals(candidate, table)))
            return TransactionTableRegistrationKind.ConnectionTemporary;

        if (Db.ListGlobalTemporaryTables(table.Schema.SchemaName).Any(candidate => ReferenceEquals(candidate, table)))
            return TransactionTableRegistrationKind.GlobalTemporary;

        return TransactionTableRegistrationKind.Schema;
    }

    private string GetRegistrationKey(TableMock table)
        => GetRegistrationKind(table) switch
        {
            TransactionTableRegistrationKind.ConnectionTemporary or TransactionTableRegistrationKind.GlobalTemporary
                => BuildTemporaryTableKey(table.TableName, table.Schema.SchemaName),
            _ => table.TableName
        };

    private void RecordCreatedTable(
        TableMock table,
        TransactionTableRegistrationKind registrationKind,
        string registrationKey)
    {
        if (CurrentTransaction == null)
            return;

        _transactionJournal.Add(new TransactionJournalEntry(
            table,
            TransactionJournalEntryKind.CreateIndex,
            -1,
            null,
            null,
            table.NextIdentity,
            registrationKind,
            registrationKey));
    }

    private void RecordDroppedTable(
        TableMock table,
        TransactionTableRegistrationKind registrationKind,
        string registrationKey)
    {
        if (CurrentTransaction == null)
            return;

        _transactionJournal.Add(new TransactionJournalEntry(
            table,
            TransactionJournalEntryKind.DropIndex,
            -1,
            null,
            null,
            table.NextIdentity,
            registrationKind,
            registrationKey));
    }

    private void RecordCreatedIndex(
        TableMock table,
        Idx indexDefinition)
    {
        if (CurrentTransaction == null)
            return;

        _transactionJournal.Add(new TransactionJournalEntry(
            table,
            TransactionJournalEntryKind.CreateIndex,
            -1,
            null,
            null,
            table.NextIdentity,
            GetRegistrationKind(table),
            GetRegistrationKey(table),
            indexDefinition));
    }

    private void RecordDroppedIndex(
        TableMock table,
        Idx indexDefinition)
    {
        if (CurrentTransaction == null)
            return;

        _transactionJournal.Add(new TransactionJournalEntry(
            table,
            TransactionJournalEntryKind.DropIndex,
            -1,
            null,
            null,
            table.NextIdentity,
            GetRegistrationKind(table),
            GetRegistrationKey(table),
            indexDefinition));
    }

    private bool TryResolveDroppedIndex(
        string indexName,
        string? tableName,
        string schemaName,
        out TableMock table,
        out Idx indexDefinition)
    {
        table = null!;
        indexDefinition = null!;
        var normalizedIndexName = indexName.NormalizeName();

        if (!string.IsNullOrWhiteSpace(tableName))
        {
            if (Db.GetTable(tableName!, schemaName) is not TableMock namedTable
                || !namedTable.Indexes.TryGetValue(normalizedIndexName, out var namedIndex))
                return false;

            table = namedTable;
            indexDefinition = new Idx(
                namedIndex.Name,
                [.. namedIndex.KeyCols],
                namedIndex.Unique,
                [.. namedIndex.Include]);
            return true;
        }

        var matchingTable = Db.ListTables(schemaName)
            .OfType<TableMock>()
            .FirstOrDefault(candidate => candidate.Indexes.TryGetValue(normalizedIndexName, out _));
        if (matchingTable is null || !matchingTable.Indexes.TryGetValue(normalizedIndexName, out var resolvedIndex))
            return false;

        table = matchingTable;
        indexDefinition = new Idx(
            resolvedIndex.Name,
            [.. resolvedIndex.KeyCols],
            resolvedIndex.Unique,
            [.. resolvedIndex.Include]);
        return true;
    }

    /// <summary>
    /// EN: Lists the tables in the current schema.
    /// PT: Lista as tabelas do schema atual.
    /// </summary>
    /// <param name="schemaName">EN: Target schema. PT: Schema alvo.</param>
    /// <returns>EN: Table list. PT: Lista de tabelas.</returns>
    public IReadOnlyList<ITableMock> ListTables(
        string? schemaName = null)
    {
        var tables = Db.ListTables(schemaName ?? Database).ToList();
        tables.AddRange(Db.ListGlobalTemporaryTables(schemaName ?? Database));
        tables.AddRange(ListTemporaryTables(schemaName));
        return tables.AsReadOnly();
    }

    /// <summary>
    /// EN: Resets all volatile in-memory state for the current connection and backing database.
    /// PT: Reseta todo o estado volátil em memória da conexão atual e do banco associado.
    /// </summary>
    public void ResetAllVolatileData()
    {
        if (!Db.ThreadSafe)
        {
            ResetAllVolatileDataCore();
            return;
        }

        lock (Db.SyncRoot)
            ResetAllVolatileDataCore();
    }

    #endregion

    #region View

    internal void AddView(
        SqlCreateViewQuery query)
    {
        var schemaName = query.Table?.DbName ?? Database;
        var viewName = query.Table?.Name?.NormalizeName();
        SqlSelectQuery? previousDefinition = null;
        if (!string.IsNullOrWhiteSpace(viewName))
            Db.TryGetView(viewName!, out previousDefinition, schemaName);

        Db.AddView(query, schemaName);
        ClearSelectPlanCache();

        if (CurrentTransaction == null || string.IsNullOrWhiteSpace(viewName))
            return;

        _transactionJournal.Add(new TransactionJournalEntry(
            null!,
            TransactionJournalEntryKind.UpsertView,
            -1,
            null,
            null,
            0,
            default,
            string.Empty,
            ViewState: new TransactionViewState(schemaName, viewName!, previousDefinition)));
    }

    internal SqlSelectQuery GetView(
        string viewName,
        string? schemaName = null)
        => Db.GetView(
            viewName,
            schemaName ?? Database);

    internal bool TryGetView(
        string viewName,
        out SqlSelectQuery? vw,
        string? schemaName = null)
        => Db.TryGetView(
            viewName,
            out vw,
            schemaName ?? Database);

    internal void DropView(
        string viewName,
        bool ifExists,
        string? schemaName = null)
    {
        var targetSchema = schemaName ?? Database;
        if (CurrentTransaction != null
            && Db.TryGetView(viewName, out var previousDefinition, targetSchema)
            && previousDefinition is not null)
        {
            _transactionJournal.Add(new TransactionJournalEntry(
                null!,
                TransactionJournalEntryKind.DropView,
                -1,
                null,
                null,
                0,
                default,
                string.Empty,
                ViewState: new TransactionViewState(targetSchema, viewName.NormalizeName(), previousDefinition)));
        }

        Db.DropView(viewName, ifExists, targetSchema);
        ClearSelectPlanCache();
    }

    internal void DropTable(
        string tableName,
        bool ifExists,
        bool temporary,
        TemporaryTableScope scope,
        string? schemaName = null)
    {
        var targetSchema = schemaName ?? Database;

        if (scope == TemporaryTableScope.Global)
        {
            if (CurrentTransaction != null
                && Db.TryGetGlobalTemporaryTable(tableName, out var globalTable, targetSchema)
                && globalTable is TableMock globalTableMock)
            {
                RecordDroppedTable(
                    globalTableMock,
                    TransactionTableRegistrationKind.GlobalTemporary,
                    BuildTemporaryTableKey(tableName, targetSchema));
            }
            Db.DropGlobalTemporaryTable(tableName, ifExists, targetSchema);
            ClearSelectPlanCache();
            return;
        }

        if (temporary || scope == TemporaryTableScope.Connection)
        {
            var temporaryKey = BuildTemporaryTableKey(tableName, targetSchema);
            if (_temporaryTables.TryGetValue(temporaryKey, out var connectionTemp)
                && connectionTemp is TableMock connectionTempMock)
            {
                if (CurrentTransaction != null)
                {
                    RecordDroppedTable(
                        connectionTempMock,
                        TransactionTableRegistrationKind.ConnectionTemporary,
                        temporaryKey);
                }

                _temporaryTables.Remove(temporaryKey);
                ClearSelectPlanCache();
                return;
            }

            if (ifExists)
            {
                ClearSelectPlanCache();
                return;
            }

            throw SqlUnsupported.ForNormalizedTableDoesNotExist(tableName);
        }

        if (CurrentTransaction != null
            && Db.TryGetTable(tableName, out var schemaTable, targetSchema)
            && schemaTable is TableMock schemaTableMock)
        {
            RecordDroppedTable(
                schemaTableMock,
                TransactionTableRegistrationKind.Schema,
                schemaTableMock.TableName);
        }

        Db.DropTable(tableName, ifExists, targetSchema);
        ClearSelectPlanCache();
    }

    internal void CreateIndex(
        string indexName,
        string tableName,
        IEnumerable<string> keyColumns,
        bool unique,
        string? schemaName = null)
    {
        Db.CreateIndex(
            indexName,
            tableName,
            keyColumns,
            unique,
            schemaName ?? Database);
        ClearSelectPlanCache();

        if (CurrentTransaction == null)
            return;

        if (Db.GetTable(tableName, schemaName ?? Database) is not TableMock table)
            return;

        var createdIndex = table.Indexes[indexName.NormalizeName()];
        RecordCreatedIndex(
            table,
            new Idx(
                createdIndex.Name,
                [.. createdIndex.KeyCols],
                createdIndex.Unique,
                [.. createdIndex.Include]));
    }

    internal void DropIndex(
        string indexName,
        bool ifExists,
        string? tableName = null,
        string? schemaName = null)
    {
        if (CurrentTransaction != null
            && TryResolveDroppedIndex(indexName, tableName, schemaName ?? Database, out var table, out var indexDefinition))
        {
            RecordDroppedIndex(table, indexDefinition);
        }

        Db.DropIndex(
            indexName,
            ifExists,
            tableName,
            schemaName ?? Database);
        ClearSelectPlanCache();
    }

    internal void AlterTableAddColumn(
        string tableName,
        string columnName,
        DbType dbType,
        bool nullable,
        int? size = null,
        int? decimalPlaces = null,
        object? defaultValue = null,
        string? schemaName = null)
    {
        Db.AlterTableAddColumn(
            tableName,
            columnName,
            dbType,
            nullable,
            size,
            decimalPlaces,
            defaultValue,
            schemaName ?? Database);
        ClearSelectPlanCache();
    }

    #endregion

    #region Procedures

    /// <summary>
    /// EN: Registers a stored procedure.
    /// PT: Registra um procedimento armazenado.
    /// </summary>
    /// <param name="procName">EN: Procedure name. PT: Nome do procedimento.</param>
    /// <param name="pr">EN: Procedure definition. PT: Definição do procedimento.</param>
    /// <param name="schemaName">EN: Target schema. PT: Schema alvo.</param>
    public void AddProdecure(
        string procName,
        ProcedureDef pr,
        string? schemaName = null)
        => Db.AddProdecure(
            procName,
            pr,
            schemaName ?? Database);

    /// <summary>
    /// EN: Tries to get a stored procedure.
    /// PT: Tenta obter um procedimento armazenado.
    /// </summary>
    /// <param name="procName">EN: Procedure name. PT: Nome do procedimento.</param>
    /// <param name="pr">EN: Found procedure, if any. PT: Procedimento encontrado, se houver.</param>
    /// <param name="schemaName">EN: Target schema. PT: Schema alvo.</param>
    /// <returns>EN: True if it exists. PT: True se existir.</returns>
    public bool TryGetProcedure(
        string procName,
        out ProcedureDef? pr,
        string? schemaName = null)
        => Db.TryGetProcedure(
            procName,
            out pr,
            schemaName ?? Database);

    #endregion

    #region Functions

    internal bool TryGetFunction(
        string functionName,
        out ScalarFunctionDef? function,
        string? schemaName = null)
        => Db.TryGetFunction(
            functionName,
            out function,
            schemaName ?? Database);

    internal void CreateFunction(
        string functionName,
        string returnTypeSql,
        IReadOnlyList<ScalarFunctionParameterDef> parameters,
        SqlExpr body,
        bool orReplace = false,
        string? schemaName = null)
    {
        var targetSchema = schemaName ?? Database;
        ScalarFunctionDef? previousDefinition = null;
        Db.TryGetFunction(functionName, out previousDefinition, targetSchema);

        Db.CreateFunction(
            functionName,
            returnTypeSql,
            parameters,
            body,
            orReplace,
            targetSchema);
        ClearSelectPlanCache();

        if (CurrentTransaction == null)
            return;

        _transactionJournal.Add(new TransactionJournalEntry(
            null!,
            TransactionJournalEntryKind.UpsertFunction,
            -1,
            null,
            null,
            0,
            default,
            string.Empty,
            FunctionState: new TransactionFunctionState(
                targetSchema,
                functionName.NormalizeName(),
                previousDefinition)));
    }

    internal void DropFunction(
        string functionName,
        bool ifExists,
        string? schemaName = null)
    {
        var targetSchema = schemaName ?? Database;
        if (CurrentTransaction != null
            && Db.TryGetFunction(functionName, out var previousDefinition, targetSchema)
            && previousDefinition is not null)
        {
            _transactionJournal.Add(new TransactionJournalEntry(
                null!,
                TransactionJournalEntryKind.DropFunction,
                -1,
                null,
                null,
                0,
                default,
                string.Empty,
                FunctionState: new TransactionFunctionState(
                    targetSchema,
                    functionName.NormalizeName(),
                    previousDefinition)));
        }

        Db.DropFunction(functionName, ifExists, targetSchema);
        ClearSelectPlanCache();
    }

    internal void CreateProcedure(
        string procedureName,
        ProcedureDef procedure,
        bool orReplace = false,
        string? schemaName = null)
    {
        var targetSchema = schemaName ?? Database;
        ProcedureDef? previousDefinition = null;
        Db.TryGetProcedure(procedureName, out previousDefinition, targetSchema);

        Db.CreateProcedure(
            procedureName,
            procedure,
            orReplace,
            targetSchema);
        ClearSelectPlanCache();

        if (CurrentTransaction == null)
            return;

        _transactionJournal.Add(new TransactionJournalEntry(
            null!,
            TransactionJournalEntryKind.UpsertProcedure,
            -1,
            null,
            null,
            0,
            default,
            string.Empty,
            ProcedureState: new TransactionProcedureState(
                targetSchema,
                procedureName.NormalizeName(),
                previousDefinition)));
    }

    internal DmlExecutionResult CreateTrigger(
        string triggerName,
        SqlTableSource table,
        bool isBefore,
        TableTriggerEvent evt,
        bool orReplace = false)
    {
        ArgumentExceptionCompatible.ThrowIfNullOrWhiteSpace(triggerName, nameof(triggerName));
        ArgumentNullExceptionCompatible.ThrowIfNull(table, nameof(table));

        var targetSchema = table.DbName ?? Database;
        var targetTable = Db.GetTable(table.Name!, targetSchema);
        if (targetTable is not TableMock tableMock)
            throw new InvalidOperationException($"Table '{table.Name}' is not a supported in-memory table type.");

        tableMock.AddOrReplaceTrigger(triggerName, evt, static _ => { }, orReplace);
        ClearSelectPlanCache();
        _ = isBefore;
        SetLastFoundRows(0);

        return new DmlExecutionResult();
    }

    internal DmlExecutionResult CreateTrigger(SqlCreateTriggerQuery query)
    {
        if (!Db.ThreadSafe)
            return CreateTrigger(
                query.TriggerName,
                query.Table!,
                query.IsBefore,
                query.Event,
                query.OrReplace);

        lock (Db.SyncRoot)
            return CreateTrigger(
                query.TriggerName,
                query.Table!,
                query.IsBefore,
                query.Event,
                query.OrReplace);
    }

    #endregion

    #region Sequences

    /// <summary>
    /// EN: Registers a sequence.
    /// PT: Registra uma sequence.
    /// </summary>
    /// <param name="sequenceName">EN: Sequence name. PT: Nome da sequence.</param>
    /// <param name="sequence">EN: Sequence definition. PT: Definição da sequence.</param>
    /// <param name="schemaName">EN: Target schema. PT: Schema alvo.</param>
    public void AddSequence(
        string sequenceName,
        SequenceDef sequence,
        string? schemaName = null)
        => Db.AddSequence(
            sequenceName,
            sequence,
            schemaName ?? Database);

    /// <summary>
    /// EN: Creates and registers a sequence.
    /// PT: Cria e registra uma sequence.
    /// </summary>
    /// <param name="sequenceName">EN: Sequence name. PT: Nome da sequence.</param>
    /// <param name="startValue">EN: First sequence value. PT: Primeiro valor da sequence.</param>
    /// <param name="incrementBy">EN: Increment step. PT: Passo de incremento.</param>
    /// <param name="currentValue">EN: Current value when known. PT: Valor atual quando conhecido.</param>
    /// <param name="schemaName">EN: Target schema. PT: Schema alvo.</param>
    /// <returns>EN: Registered sequence. PT: Sequence registrada.</returns>
    public SequenceDef AddSequence(
        string sequenceName,
        long startValue = 1,
        long incrementBy = 1,
        long? currentValue = null,
        string? schemaName = null)
        => Db.AddSequence(
            sequenceName,
            startValue,
            incrementBy,
            currentValue,
            schemaName ?? Database);

    /// <summary>
    /// EN: Tries to get a sequence.
    /// PT: Tenta obter uma sequence.
    /// </summary>
    /// <param name="sequenceName">EN: Sequence name. PT: Nome da sequence.</param>
    /// <param name="sequence">EN: Found sequence, if any. PT: Sequence encontrada, se houver.</param>
    /// <param name="schemaName">EN: Target schema. PT: Schema alvo.</param>
    /// <returns>EN: True if it exists. PT: True se existir.</returns>
    public bool TryGetSequence(
        string sequenceName,
        out SequenceDef? sequence,
        string? schemaName = null)
        => Db.TryGetSequence(
            sequenceName,
            out sequence,
            schemaName ?? Database);

    internal void CreateSequence(
        string sequenceName,
        bool ifNotExists,
        long startValue = 1,
        long incrementBy = 1,
        string? schemaName = null)
    {
        var targetSchema = schemaName ?? Database;
        var existedBefore = Db.TryGetSequence(sequenceName, out _, targetSchema);
        Db.CreateSequence(
            sequenceName,
            ifNotExists,
            startValue,
            incrementBy,
            targetSchema);
        ClearSelectPlanCache();

        if (CurrentTransaction == null || existedBefore)
            return;

        _transactionJournal.Add(new TransactionJournalEntry(
            null!,
            TransactionJournalEntryKind.CreateSequence,
            -1,
            null,
            null,
            0,
            default,
            string.Empty,
            SequenceState: new TransactionSequenceState(
                targetSchema,
                sequenceName.NormalizeName(),
                null,
                false,
                default)));
    }

    internal void DropSequence(
        string sequenceName,
        bool ifExists,
        string? schemaName = null)
    {
        var targetSchema = schemaName ?? Database;
        if (CurrentTransaction != null
            && Db.TryGetSequence(sequenceName, out var previousSequence, targetSchema)
            && previousSequence is not null)
        {
            var hadSessionValue = TryGetSessionSequenceValue(sequenceName, out var sessionValue, targetSchema);
            _transactionJournal.Add(new TransactionJournalEntry(
                null!,
                TransactionJournalEntryKind.DropSequence,
                -1,
                null,
                null,
                0,
                default,
                string.Empty,
                SequenceState: new TransactionSequenceState(
                    targetSchema,
                    sequenceName.NormalizeName(),
                    CloneSequence(previousSequence),
                    hadSessionValue,
                    sessionValue)));
        }

        ClearSessionSequenceValue(sequenceName, targetSchema);
        Db.DropSequence(sequenceName, ifExists, targetSchema);
        ClearSelectPlanCache();
    }

    private static SequenceDef CloneSequence(SequenceDef sequence)
    {
        var clone = new SequenceDef(
            sequence.Name,
            sequence.StartValue,
            sequence.IncrementBy,
            sequence.CurrentValue);
        if (sequence.CurrentValue.HasValue && !sequence.IsCalled)
            clone.SetValue(sequence.CurrentValue.Value, false);

        return clone;
    }

    internal void CaptureSequenceStateForRollback(
        string sequenceName,
        string? schemaName = null)
    {
        if (CurrentTransaction == null
            || !Db.TryGetSequence(sequenceName, out var sequence, schemaName ?? Database)
            || sequence is null)
            return;

        var targetSchema = schemaName ?? Database;
        var hadSessionValue = TryGetSessionSequenceValue(sequenceName, out var sessionValue, targetSchema);
        _transactionJournal.Add(new TransactionJournalEntry(
            null!,
            TransactionJournalEntryKind.UpdateSequence,
            -1,
            null,
            null,
            0,
            default,
            string.Empty,
            SequenceState: new TransactionSequenceState(
                targetSchema,
                sequenceName.NormalizeName(),
                CloneSequence(sequence),
                hadSessionValue,
                sessionValue)));
    }

    internal void SetSessionSequenceValue(
        string sequenceName,
        long value,
        string? schemaName = null)
    {
        var key = BuildSessionSequenceKey(sequenceName, schemaName);
        _sessionSequenceValues[key] = value;
        _lastSessionSequenceKey = key;
    }

    internal bool TryGetSessionSequenceValue(
        string sequenceName,
        out long value,
        string? schemaName = null)
        => _sessionSequenceValues.TryGetValue(BuildSessionSequenceKey(sequenceName, schemaName), out value);

    internal bool TryGetLastSessionSequenceValue(out long value)
    {
        value = default;
        return _lastSessionSequenceKey is not null
            && _sessionSequenceValues.TryGetValue(_lastSessionSequenceKey, out value);
    }

    internal void SetSessionContextValue(string key, object? value)
    {
        if (string.IsNullOrWhiteSpace(key))
            return;

        _sessionContextValues[key] = value;
    }

    internal bool TryGetSessionContextValue(string key, out object? value)
        => _sessionContextValues.TryGetValue(key, out value);

    internal void SetContextInfo(byte[]? value)
        => _contextInfo = value;

    internal byte[]? GetContextInfo()
        => _contextInfo;

    private string BuildSessionSequenceKey(
        string sequenceName,
        string? schemaName)
    {
        var schema = Db.GetSchemaName(schemaName ?? Database);
        return $"{schema}:{sequenceName.NormalizeName()}";
    }

    private void ClearSessionSequenceValue(
        string sequenceName,
        string? schemaName)
    {
        var key = BuildSessionSequenceKey(sequenceName, schemaName);
        _sessionSequenceValues.Remove(key);
        if (string.Equals(_lastSessionSequenceKey, key, StringComparison.OrdinalIgnoreCase))
            _lastSessionSequenceKey = null;
    }

    #endregion

    /// <summary>
    /// EN: Begins a database transaction with the specified isolation level.
    /// PT: Inicia uma transação com o nível de isolamento especificado.
    /// </summary>
    /// <param name="isolationLevel">EN: Isolation level. PT: Nível de isolamento.</param>
    /// <returns>EN: Created transaction. PT: Transação criada.</returns>
    protected override DbTransaction BeginDbTransaction(
        IsolationLevel isolationLevel)
    {
        if (!Db.ThreadSafe)
            return BeginTransactionCore(isolationLevel);

        lock (Db.SyncRoot)
            return BeginTransactionCore(isolationLevel);
    }

    private DbTransaction BeginTransactionCore(IsolationLevel isolationLevel)
    {
        CurrentIsolationLevel = isolationLevel;
        CurrentTransaction = CreateTransaction(isolationLevel);
        ClearTransactionStateCore();
        AttachTransactionJournalToCurrentTables();
        _transactionBeginJournalPosition = _transactionJournal.Count;
        if (SupportsSavepoints)
            CreateSavepointCore("__tx_begin__");
        return CurrentTransaction;
    }

    /// <summary>
    /// EN: Creates a provider-specific transaction instance.
    /// PT: Cria uma instância de transação específica do provedor.
    /// </summary>
    /// <returns>EN: Transaction instance. PT: Instância da transação.</returns>
    protected abstract DbTransaction CreateTransaction(IsolationLevel isolationLevel);

    /// <summary>
    /// EN: Changes the current database/schema of the connection.
    /// PT: Altera o database/schema atual da conexão.
    /// </summary>
    /// <param name="databaseName">EN: Database name. PT: Nome do database.</param>
    public override void ChangeDatabase(string databaseName)
    {
        _database = databaseName;
        ClearSelectPlanCache();
    }

    /// <summary>
    /// EN: Closes the simulated connection.
    /// PT: Fecha a conexão simulada.
    /// </summary>
    public override void Close()
    {
        if (!Db.ThreadSafe)
        {
            CloseCore();
            return;
        }

        lock (Db.SyncRoot)
            CloseCore();
    }

    private void CloseCore()
    {
        CurrentTransaction?.Dispose();
        CurrentTransaction = null;
        CurrentIsolationLevel = IsolationLevel.Unspecified;
        ClearTransactionStateCore();

        foreach (var table in _temporaryTables.Values)
        {
            while (table.Count > 0)
                table.RemoveAt(table.Count - 1);

            table.NextIdentity = 1;
        }

        _temporaryTables.Clear();
        _sessionSequenceValues.Clear();
        _sessionContextValues.Clear();
        _contextInfo = null;
        _lastInsertId = 0;
        _lastSessionSequenceKey = null;
        SetLastFoundRows(0);
        ClearExecutionPlans();
        ClearSelectPlanCache();
        _state = ConnectionState.Closed;
    }

    /// <summary>
    /// EN: Creates a command associated with the current transaction.
    /// PT: Cria um comando associado à transação atual.
    /// </summary>
    /// <returns>EN: Command instance. PT: Instância do comando.</returns>
    protected override DbCommand CreateDbCommand()
        => CreateDbCommandCore(CurrentTransaction);

    /// <summary>
    /// EN: Creates a provider-specific command tied to a transaction.
    /// PT: Cria um comando específico do provedor atrelado a uma transação.
    /// </summary>
    /// <param name="transaction">EN: Current transaction. PT: Transação atual.</param>
    /// <returns>EN: Command instance. PT: Instância do comando.</returns>
    protected abstract DbCommand CreateDbCommandCore(
        DbTransaction? transaction);

    /// <summary>
    /// EN: Opens the simulated connection.
    /// PT: Abre a conexão simulada.
    /// </summary>
    public override void Open()
    {
        _state = ConnectionState.Open;
        Debug.WriteLine("Opended");
    }

    /// <summary>
    /// EN: Commits the current transaction, releasing backups.
    /// PT: Confirma a transação atual, liberando backups.
    /// </summary>
    public void CommitTransaction()
    {
        if (!Db.ThreadSafe)
        {
            CommitCore();
            return;
        }

        lock (Db.SyncRoot)
            CommitCore();
    }

    private void CommitCore()
    {
        Debug.WriteLine("Transaction Committed");
        ClearTransactionStateCore();
        CurrentTransaction = null;
        CurrentIsolationLevel = IsolationLevel.Unspecified;
    }

    /// <summary>
    /// EN: Rolls back the current transaction restoring the backup.
    /// PT: Desfaz a transação atual restaurando o backup.
    /// </summary>
    public void RollbackTransaction()
    {
        if (!Db.ThreadSafe)
        {
            RollbackCore();
            return;
        }

        lock (Db.SyncRoot)
            RollbackCore();
    }

    private void RollbackCore()
    {
        if (CurrentTransaction == null)
            return;

        Debug.WriteLine("Transaction Rolled Back");
        RollbackJournalTo(_transactionBeginJournalPosition);
        ClearTransactionStateCore();
        CurrentTransaction = null;
        CurrentIsolationLevel = IsolationLevel.Unspecified;
    }

    /// <summary>
    /// EN: Creates a named savepoint inside the active transaction.
    /// PT: Cria um savepoint nomeado dentro da transação ativa.
    /// </summary>
    /// <param name="savepointName">EN: Savepoint name. PT: Nome do savepoint.</param>
    public void CreateSavepoint(string savepointName)
    {
        if (!Db.ThreadSafe)
        {
            CreateSavepointCore(savepointName);
            return;
        }

        lock (Db.SyncRoot)
            CreateSavepointCore(savepointName);
    }

    /// <summary>
    /// EN: Rolls back to a named savepoint inside the active transaction.
    /// PT: Executa rollback para um savepoint nomeado dentro da transação ativa.
    /// </summary>
    /// <param name="savepointName">EN: Savepoint name. PT: Nome do savepoint.</param>
    public void RollbackTransaction(string savepointName)
    {
        if (!Db.ThreadSafe)
        {
            RollbackToSavepointCore(savepointName);
            return;
        }

        lock (Db.SyncRoot)
            RollbackToSavepointCore(savepointName);
    }

    /// <summary>
    /// EN: Releases a named savepoint from the active transaction.
    /// PT: Libera um savepoint nomeado da transação ativa.
    /// </summary>
    /// <param name="savepointName">EN: Savepoint name. PT: Nome do savepoint.</param>
    public void ReleaseSavepoint(string savepointName)
    {
        if (!Db.ThreadSafe)
        {
            ReleaseSavepointCore(savepointName);
            return;
        }

        lock (Db.SyncRoot)
            ReleaseSavepointCore(savepointName);
    }

    private void CreateSavepointCore(string savepointName)
    {
        EnsureActiveTransaction();
        if (!SupportsSavepoints)
            throw SqlUnsupported.ForDialect(ExecutionDialect, "SAVEPOINT");

        var normalizedName = NormalizeSavepointName(savepointName);
        if (_savepoints.ContainsKey(normalizedName))
            _savepointOrder.Remove(normalizedName);
        _savepoints[normalizedName] = _transactionJournal.Count;
        _savepointOrder.Add(normalizedName);
    }

    private void RollbackToSavepointCore(string savepointName)
    {
        EnsureActiveTransaction();
        if (!SupportsSavepoints)
            throw SqlUnsupported.ForDialect(ExecutionDialect, "ROLLBACK TO SAVEPOINT");

        var normalizedName = NormalizeSavepointName(savepointName);
        if (!_savepoints.TryGetValue(normalizedName, out var journalPosition))
            throw SqlUnsupported.ForSavepointNotFound(savepointName);

        RollbackJournalTo(journalPosition);

        var savepointIndex = _savepointOrder.FindIndex(name => name.Equals(normalizedName, StringComparison.OrdinalIgnoreCase));
        if (savepointIndex >= 0)
        {
            for (var idx = _savepointOrder.Count - 1; idx > savepointIndex; idx--)
            {
                _savepoints.Remove(_savepointOrder[idx]);
                _savepointOrder.RemoveAt(idx);
            }
        }
    }

    private void ReleaseSavepointCore(string savepointName)
    {
        EnsureActiveTransaction();
        if (!SupportsSavepoints || !SupportsReleaseSavepoint)
            throw SqlUnsupported.ForDialect(ExecutionDialect, "RELEASE SAVEPOINT");

        var normalizedName = NormalizeSavepointName(savepointName);
        if (!_savepoints.Remove(normalizedName))
            throw SqlUnsupported.ForSavepointNotFound(savepointName);

        _savepointOrder.RemoveAll(name => name.Equals(normalizedName, StringComparison.OrdinalIgnoreCase));
    }

    private static string NormalizeSavepointName(string savepointName)
    {
        ArgumentExceptionCompatible.ThrowIfNullOrWhiteSpace(savepointName, nameof(savepointName));
        return savepointName.Trim();
    }

    private void EnsureActiveTransaction()
    {
        if (CurrentTransaction == null)
            throw SqlUnsupported.ForNoActiveTransactionForSavepointOperation();
    }

    private void AttachTransactionJournalToCurrentTables()
    {
        var allTables = Db.ListAllTablesBestEffort()
            .Concat(_temporaryTables.Values)
            .Distinct(TableReferenceComparer.Instance);

        foreach (var table in allTables)
            AttachTransactionJournal(table);
    }

    private void AttachTransactionJournal(ITableMock table)
    {
        if (table is not TableMock tableMock || !_journalObservedTables.Add(tableMock))
            return;

        tableMock.MutationApplied += OnTableMutationApplied;
    }

    private void OnTableMutationApplied(TableMutationNotification mutation)
    {
        if (_isReplayingTransactionJournal || CurrentTransaction == null)
            return;

        _transactionJournal.Add(new TransactionJournalEntry(
            mutation.Table,
            mutation.Kind switch
            {
                TableMutationKind.Insert => TransactionJournalEntryKind.Insert,
                TableMutationKind.Update => TransactionJournalEntryKind.Update,
                _ => TransactionJournalEntryKind.Delete
            },
            mutation.RowIndex,
            mutation.Row,
            mutation.OldRowSnapshot,
            mutation.PreviousNextIdentity,
            GetRegistrationKind(mutation.Table),
            GetRegistrationKey(mutation.Table)));
    }

    private void RollbackJournalTo(int journalPosition)
    {
        if (_transactionJournal.Count <= journalPosition)
            return;

        var touchedTables = new HashSet<TableMock>();
        _isReplayingTransactionJournal = true;
        try
        {
            for (var idx = _transactionJournal.Count - 1; idx >= journalPosition; idx--)
            {
                var entry = _transactionJournal[idx];
                if (entry.Table is not null)
                    touchedTables.Add(entry.Table);
                switch (entry.Kind)
                {
                    case TransactionJournalEntryKind.Insert:
                        entry.Table!.RemoveRowByReference(entry.Row!);
                        entry.Table.NextIdentity = entry.PreviousNextIdentity;
                        break;
                    case TransactionJournalEntryKind.Update:
                        entry.Table!.RestoreRowSnapshot(
                            entry.Row!,
                            entry.OldRowSnapshot ?? new Dictionary<int, object?>());
                        break;
                    case TransactionJournalEntryKind.Delete:
                        entry.Table!.InsertRestoredRow(entry.RowIndex, entry.Row!);
                        break;
                    case TransactionJournalEntryKind.CreateTable:
                        UnregisterTable(entry.Table!, entry.RegistrationKind, entry.RegistrationKey);
                        break;
                    case TransactionJournalEntryKind.DropTable:
                        RegisterTable(entry.Table!, entry.RegistrationKind, entry.RegistrationKey);
                        break;
                    case TransactionJournalEntryKind.CreateIndex:
                        if (entry.IndexDefinition is not null)
                            entry.Table!.DropIndex(entry.IndexDefinition.Name, ifExists: true);
                        break;
                    case TransactionJournalEntryKind.DropIndex:
                        if (entry.IndexDefinition is not null
                            && !entry.Table!.Indexes.ContainsKey(entry.IndexDefinition.Name))
                        {
                            entry.Table.CreateIndex(
                                entry.IndexDefinition.Name,
                                entry.IndexDefinition.KeyCols,
                                [.. entry.IndexDefinition.Include],
                                entry.IndexDefinition.Unique);
                        }
                        break;
                    case TransactionJournalEntryKind.UpsertView:
                        if (entry.ViewState is not null)
                        {
                            if (entry.ViewState.PreviousDefinition is null)
                                Db.RemoveView(entry.ViewState.ViewName, entry.ViewState.SchemaName);
                            else
                                Db.RestoreView(
                                    entry.ViewState.ViewName,
                                    entry.ViewState.PreviousDefinition,
                                    entry.ViewState.SchemaName);
                        }
                        break;
                    case TransactionJournalEntryKind.DropView:
                        if (entry.ViewState?.PreviousDefinition is not null)
                        {
                            Db.RestoreView(
                                entry.ViewState.ViewName,
                                entry.ViewState.PreviousDefinition,
                                entry.ViewState.SchemaName);
                        }
                        break;
                    case TransactionJournalEntryKind.CreateSequence:
                        if (entry.SequenceState is not null)
                        {
                            Db.DropSequence(entry.SequenceState.SequenceName, true, entry.SequenceState.SchemaName);
                            ClearSessionSequenceValue(entry.SequenceState.SequenceName, entry.SequenceState.SchemaName);
                        }
                        break;
                    case TransactionJournalEntryKind.DropSequence:
                        if (entry.SequenceState?.PreviousDefinition is not null)
                        {
                            Db.RestoreSequence(
                                entry.SequenceState.SequenceName,
                                CloneSequence(entry.SequenceState.PreviousDefinition),
                                entry.SequenceState.SchemaName);
                            if (entry.SequenceState.HadSessionValue)
                                SetSessionSequenceValue(entry.SequenceState.SequenceName, entry.SequenceState.SessionValue, entry.SequenceState.SchemaName);
                            else
                                ClearSessionSequenceValue(entry.SequenceState.SequenceName, entry.SequenceState.SchemaName);
                        }
                        break;
                    case TransactionJournalEntryKind.UpdateSequence:
                        if (entry.SequenceState?.PreviousDefinition is not null)
                        {
                            Db.RestoreSequence(
                                entry.SequenceState.SequenceName,
                                CloneSequence(entry.SequenceState.PreviousDefinition),
                                entry.SequenceState.SchemaName);
                            if (entry.SequenceState.HadSessionValue)
                                SetSessionSequenceValue(entry.SequenceState.SequenceName, entry.SequenceState.SessionValue, entry.SequenceState.SchemaName);
                            else
                                ClearSessionSequenceValue(entry.SequenceState.SequenceName, entry.SequenceState.SchemaName);
                        }
                        break;
                    case TransactionJournalEntryKind.UpsertFunction:
                        if (entry.FunctionState is not null)
                        {
                            if (entry.FunctionState.PreviousDefinition is null)
                                Db.RemoveFunction(entry.FunctionState.FunctionName, entry.FunctionState.SchemaName);
                            else
                                Db.RestoreFunction(
                                    entry.FunctionState.FunctionName,
                                    entry.FunctionState.PreviousDefinition,
                                    entry.FunctionState.SchemaName);
                        }
                        break;
                    case TransactionJournalEntryKind.DropFunction:
                        if (entry.FunctionState?.PreviousDefinition is not null)
                        {
                            Db.RestoreFunction(
                                entry.FunctionState.FunctionName,
                                entry.FunctionState.PreviousDefinition,
                                entry.FunctionState.SchemaName);
                        }
                        break;
                    case TransactionJournalEntryKind.UpsertProcedure:
                        if (entry.ProcedureState is not null)
                        {
                            if (entry.ProcedureState.PreviousDefinition is null)
                                Db.RemoveProcedure(entry.ProcedureState.ProcedureName, entry.ProcedureState.SchemaName);
                            else
                                Db.RestoreProcedure(
                                    entry.ProcedureState.ProcedureName,
                                    entry.ProcedureState.PreviousDefinition,
                                    entry.ProcedureState.SchemaName);
                        }
                        break;
                }
            }
        }
        finally
        {
            _isReplayingTransactionJournal = false;
        }

        _transactionJournal.RemoveRange(
            journalPosition,
            _transactionJournal.Count - journalPosition);

        var touchedTableList = touchedTables.ToArray();
        if (Db.ThreadSafe && touchedTableList.Length > 1)
            Parallel.ForEach(touchedTableList, table => table.RestoreIndexesAfterJournalReplay());
        else
            foreach (var table in touchedTableList)
                table.RestoreIndexesAfterJournalReplay();
    }

    private void RegisterTable(
        TableMock table,
        TransactionTableRegistrationKind registrationKind,
        string registrationKey)
    {
        switch (registrationKind)
        {
            case TransactionTableRegistrationKind.ConnectionTemporary:
                _temporaryTables[registrationKey] = table;
                break;
            case TransactionTableRegistrationKind.GlobalTemporary:
                Db.RestoreGlobalTemporaryTable(table, table.Schema.SchemaName);
                break;
            default:
                table.Schema.Tables[table.TableName] = table;
                break;
        }
    }

    private void UnregisterTable(
        TableMock table,
        TransactionTableRegistrationKind registrationKind,
        string registrationKey)
    {
        switch (registrationKind)
        {
            case TransactionTableRegistrationKind.ConnectionTemporary:
                _temporaryTables.Remove(registrationKey);
                break;
            case TransactionTableRegistrationKind.GlobalTemporary:
                Db.RemoveGlobalTemporaryTable(table.TableName, table.Schema.SchemaName);
                break;
            default:
                table.Schema.Tables.Remove(table.TableName);
                break;
        }
    }

    private void ClearTransactionStateCore()
    {
        var observedTables = _journalObservedTables.ToArray();
        if (Db.ThreadSafe && observedTables.Length > 1)
            Parallel.ForEach(observedTables, table => table.MutationApplied -= OnTableMutationApplied);
        else
            foreach (var table in observedTables)
                table.MutationApplied -= OnTableMutationApplied;

        _journalObservedTables.Clear();
        _transactionJournal.Clear();
        _savepoints.Clear();
        _savepointOrder.Clear();
        _transactionBeginJournalPosition = 0;
        _isReplayingTransactionJournal = false;
    }

    private void ResetAllVolatileDataCore()
    {
        CurrentTransaction?.Dispose();
        CurrentTransaction = null;
        CurrentIsolationLevel = IsolationLevel.Unspecified;
        ClearTransactionStateCore();

        Db.ResetVolatileData(includeGlobalTemporaryTables: true);

        foreach (var table in _temporaryTables.Values)
        {
            while (table.Count > 0)
                table.RemoveAt(table.Count - 1);

            table.NextIdentity = 1;
        }

        _temporaryTables.Clear();
    }

    internal void MaybeDelayOrDrop()
    {
        if (DropProbability > 0 && new Random().NextDouble() < DropProbability)
            throw new IOException("Simulated network drop");
        if (SimulatedLatencyMs > 0)
            Thread.Sleep(SimulatedLatencyMs);
    }

    protected internal abstract Exception NewException(string message, int code);

    /// <summary>
    /// EN: Disposes the connection and associated resources.
    /// PT: Descarta a conexão e os recursos associados.
    /// </summary>
    /// <param name="disposing">EN: True to dispose managed resources. PT: True para descartar recursos gerenciados.</param>
    protected override void Dispose(bool disposing)
    {
        if (_disposed)
        {
            base.Dispose(disposing);
            return;
        }

        if (disposing)
        {
            CurrentTransaction?.Dispose();
            _temporaryTables.Clear();
        }

        _disposed = true;
        base.Dispose(disposing);
    }
}
