//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbSqlLikeMem.VisualStudioExtension.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DbSqlLikeMem.VisualStudioExtension.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add connection.
        /// </summary>
        public static string AddConnectionButton {
            get {
                return ResourceManager.GetString("AddConnectionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string ApplyButton {
            get {
                return ResourceManager.GetString("ApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel operation.
        /// </summary>
        public static string CancelOperationMenu {
            get {
                return ResourceManager.GetString("CancelOperationMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check consistency.
        /// </summary>
        public static string CheckConsistencyMenu {
            get {
                return ResourceManager.GetString("CheckConsistencyMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking consistency....
        /// </summary>
        public static string CheckingConsistency {
            get {
                return ResourceManager.GetString("CheckingConsistency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all.
        /// </summary>
        public static string ClearAllButton {
            get {
                return ResourceManager.GetString("ClearAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear filter.
        /// </summary>
        public static string ClearFilterMenu {
            get {
                return ResourceManager.GetString("ClearFilterMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure mappings.
        /// </summary>
        public static string ConfigureMappingsMenu {
            get {
                return ResourceManager.GetString("ConfigureMappingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure templates.
        /// </summary>
        public static string ConfigureTemplatesMenu {
            get {
                return ResourceManager.GetString("ConfigureTemplatesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string ConfirmTitle {
            get {
                return ResourceManager.GetString("ConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add connection.
        /// </summary>
        public static string ConnectionDialogTitle {
            get {
                return ResourceManager.GetString("ConnectionDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failure.
        /// </summary>
        public static string ConnectionFailureTitle {
            get {
                return ResourceManager.GetString("ConnectionFailureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection not found..
        /// </summary>
        public static string ConnectionNotFound {
            get {
                return ResourceManager.GetString("ConnectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection String:.
        /// </summary>
        public static string ConnectionStringLabel {
            get {
                return ResourceManager.GetString("ConnectionStringLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection validated successfully..
        /// </summary>
        public static string ConnectionValidatedSuccessfully {
            get {
                return ResourceManager.GetString("ConnectionValidatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consistency check finished for {0} object(s)..
        /// </summary>
        public static string ConsistencyCheckCompletedCount {
            get {
                return ResourceManager.GetString("ConsistencyCheckCompletedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        public static string ContainsOption {
            get {
                return ResourceManager.GetString("ContainsOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database:.
        /// </summary>
        public static string DatabaseLabel {
            get {
                return ResourceManager.GetString("DatabaseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit connection.
        /// </summary>
        public static string EditConnectionMenu {
            get {
                return ResourceManager.GetString("EditConnectionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exact.
        /// </summary>
        public static string ExactOption {
            get {
                return ResourceManager.GetString("ExactOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export settings.
        /// </summary>
        public static string ExportSettingsButton {
            get {
                return ResourceManager.GetString("ExportSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export settings.
        /// </summary>
        public static string ExportSettingsDialogTitle {
            get {
                return ResourceManager.GetString("ExportSettingsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract scenario.
        /// </summary>
        public static string ExtractScenarioButton {
            get {
                return ResourceManager.GetString("ExtractScenarioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract test scenario.
        /// </summary>
        public static string ExtractTestScenarioMenu {
            get {
                return ResourceManager.GetString("ExtractTestScenarioMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create connection..
        /// </summary>
        public static string FailedCreateConnection {
            get {
                return ResourceManager.GetString("FailedCreateConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File pattern:.
        /// </summary>
        public static string FilePatternLabel {
            get {
                return ResourceManager.GetString("FilePatternLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in name and connection string..
        /// </summary>
        public static string FillConnectionNameAndString {
            get {
                return ResourceManager.GetString("FillConnectionNameAndString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in file pattern and output directory..
        /// </summary>
        public static string FillMappingPatternAndOutput {
            get {
                return ResourceManager.GetString("FillMappingPatternAndOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter items....
        /// </summary>
        public static string FilterItemsMenu {
            get {
                return ResourceManager.GetString("FilterItemsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter:.
        /// </summary>
        public static string FilterLabel {
            get {
                return ResourceManager.GetString("FilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Filter (WHERE):.
        /// </summary>
        public static string FilterSqlLabel {
            get {
                return ResourceManager.GetString("FilterSqlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign keys.
        /// </summary>
        public static string ForeignKeysLabel {
            get {
                return ResourceManager.GetString("ForeignKeysLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate all classes.
        /// </summary>
        public static string GenerateAllClassesMenu {
            get {
                return ResourceManager.GetString("GenerateAllClassesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate classes.
        /// </summary>
        public static string GenerateClassesTitle {
            get {
                return ResourceManager.GetString("GenerateClassesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate model classes.
        /// </summary>
        public static string GenerateModelClassesMenu {
            get {
                return ResourceManager.GetString("GenerateModelClassesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate repository classes.
        /// </summary>
        public static string GenerateRepositoryClassesMenu {
            get {
                return ResourceManager.GetString("GenerateRepositoryClassesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate test classes.
        /// </summary>
        public static string GenerateTestClassesMenu {
            get {
                return ResourceManager.GetString("GenerateTestClassesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import settings.
        /// </summary>
        public static string ImportSettingsButton {
            get {
                return ResourceManager.GetString("ImportSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import settings.
        /// </summary>
        public static string ImportSettingsDialogTitle {
            get {
                return ResourceManager.GetString("ImportSettingsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include parent table data (FK).
        /// </summary>
        public static string IncludeParentsCheckbox {
            get {
                return ResourceManager.GetString("IncludeParentsCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexes.
        /// </summary>
        public static string IndexesLabel {
            get {
                return ResourceManager.GetString("IndexesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid directory or permission denied: {0}. Detail: {1}.
        /// </summary>
        public static string InvalidDirectoryWithDetail {
            get {
                return ResourceManager.GetString("InvalidDirectoryWithDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid export path..
        /// </summary>
        public static string InvalidExportPath {
            get {
                return ResourceManager.GetString("InvalidExportPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid import path..
        /// </summary>
        public static string InvalidImportPath {
            get {
                return ResourceManager.GetString("InvalidImportPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid local state. Starting with empty configuration..
        /// </summary>
        public static string InvalidLocalStateStartingEmpty {
            get {
                return ResourceManager.GetString("InvalidLocalStateStartingEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or empty settings file..
        /// </summary>
        public static string InvalidOrEmptySettingsFile {
            get {
                return ResourceManager.GetString("InvalidOrEmptySettingsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON files (*.json)|*.json|All files (*.*)|*.*.
        /// </summary>
        public static string JsonFileFilter {
            get {
                return ResourceManager.GetString("JsonFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load data.
        /// </summary>
        public static string LoadDataButton {
            get {
                return ResourceManager.GetString("LoadDataButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure mappings.
        /// </summary>
        public static string MappingDialogTitle {
            get {
                return ResourceManager.GetString("MappingDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping not found for selected connection..
        /// </summary>
        public static string MappingNotFoundForConnection {
            get {
                return ResourceManager.GetString("MappingNotFoundForConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mappings updated..
        /// </summary>
        public static string MappingsUpdated {
            get {
                return ResourceManager.GetString("MappingsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing generated files (class/model/repository)..
        /// </summary>
        public static string MissingGeneratedFiles {
            get {
                return ResourceManager.GetString("MissingGeneratedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode:.
        /// </summary>
        public static string ModeLabel {
            get {
                return ResourceManager.GetString("ModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model output:.
        /// </summary>
        public static string ModelOutputLabel {
            get {
                return ResourceManager.GetString("ModelOutputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model template:.
        /// </summary>
        public static string ModelTemplateLabel {
            get {
                return ResourceManager.GetString("ModelTemplateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No object selected for generation..
        /// </summary>
        public static string NoObjectSelectedForGeneration {
            get {
                return ResourceManager.GetString("NoObjectSelectedForGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No objects loaded to check consistency..
        /// </summary>
        public static string NoObjectsLoadedForConsistency {
            get {
                return ResourceManager.GetString("NoObjectsLoadedForConsistency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No objects loaded to generate..
        /// </summary>
        public static string NoObjectsLoadedForGeneration {
            get {
                return ResourceManager.GetString("NoObjectsLoadedForGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No objects loaded to generate. Use Refresh objects first..
        /// </summary>
        public static string NoObjectsLoadedUseRefresh {
            get {
                return ResourceManager.GetString("NoObjectsLoadedUseRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tables found in this connection..
        /// </summary>
        public static string NoTablesFoundInConnection {
            get {
                return ResourceManager.GetString("NoTablesFoundInConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item filter.
        /// </summary>
        public static string ObjectFilterDialogTitle {
            get {
                return ResourceManager.GetString("ObjectFilterDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects updated for {0} connection(s)..
        /// </summary>
        public static string ObjectsUpdatedCount {
            get {
                return ResourceManager.GetString("ObjectsUpdatedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An operation is already in progress..
        /// </summary>
        public static string OperationAlreadyInProgress {
            get {
                return ResourceManager.GetString("OperationAlreadyInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide output directories for Model and Repository..
        /// </summary>
        public static string OutputDirectoriesRequired {
            get {
                return ResourceManager.GetString("OutputDirectoriesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output directory:.
        /// </summary>
        public static string OutputDirectoryLabel {
            get {
                return ResourceManager.GetString("OutputDirectoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} file(s) already exist and will be overwritten:{1}{1}{2}.
        /// </summary>
        public static string OverwritePreviewMessage {
            get {
                return ResourceManager.GetString("OverwritePreviewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite preview.
        /// </summary>
        public static string OverwritePreviewTitle {
            get {
                return ResourceManager.GetString("OverwritePreviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial update ({0} failure(s)). See logs for details..
        /// </summary>
        public static string PartialUpdateFailureCount {
            get {
                return ResourceManager.GetString("PartialUpdateFailureCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a scenario name..
        /// </summary>
        public static string ProvideScenarioNameMessage {
            get {
                return ResourceManager.GetString("ProvideScenarioNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh objects.
        /// </summary>
        public static string RefreshObjectsButton {
            get {
                return ResourceManager.GetString("RefreshObjectsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove connection.
        /// </summary>
        public static string RemoveConnectionMenu {
            get {
                return ResourceManager.GetString("RemoveConnectionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove connection &apos;{0}&apos;?.
        /// </summary>
        public static string RemoveConnectionQuestion {
            get {
                return ResourceManager.GetString("RemoveConnectionQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository output:.
        /// </summary>
        public static string RepositoryOutputLabel {
            get {
                return ResourceManager.GetString("RepositoryOutputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository template:.
        /// </summary>
        public static string RepositoryTemplateLabel {
            get {
                return ResourceManager.GetString("RepositoryTemplateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario extracted successfully: {0}.
        /// </summary>
        public static string ScenarioExtractedSuccessfullyPath {
            get {
                return ResourceManager.GetString("ScenarioExtractedSuccessfullyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario extracted successfully.{0}File: {1}.
        /// </summary>
        public static string ScenarioExtractedWithFile {
            get {
                return ResourceManager.GetString("ScenarioExtractedWithFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario name:.
        /// </summary>
        public static string ScenarioNameLabel {
            get {
                return ResourceManager.GetString("ScenarioNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        public static string SelectAllButton {
            get {
                return ResourceManager.GetString("SelectAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least one row for extraction..
        /// </summary>
        public static string SelectAtLeastOneRowMessage {
            get {
                return ResourceManager.GetString("SelectAtLeastOneRowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a connection node to edit..
        /// </summary>
        public static string SelectConnectionToEdit {
            get {
                return ResourceManager.GetString("SelectConnectionToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a connection node to remove..
        /// </summary>
        public static string SelectConnectionToRemove {
            get {
                return ResourceManager.GetString("SelectConnectionToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a connection, object type or object to check consistency..
        /// </summary>
        public static string SelectNodeToCheckConsistency {
            get {
                return ResourceManager.GetString("SelectNodeToCheckConsistency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a connection, object type or table to extract scenario..
        /// </summary>
        public static string SelectNodeToExtractScenario {
            get {
                return ResourceManager.GetString("SelectNodeToExtractScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a connection, object type or object to generate classes..
        /// </summary>
        public static string SelectNodeToGenerateClasses {
            get {
                return ResourceManager.GetString("SelectNodeToGenerateClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a connection, object type or object to generate model classes..
        /// </summary>
        public static string SelectNodeToGenerateModelClasses {
            get {
                return ResourceManager.GetString("SelectNodeToGenerateModelClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a connection, object type or object to generate repository classes..
        /// </summary>
        public static string SelectNodeToGenerateRepositoryClasses {
            get {
                return ResourceManager.GetString("SelectNodeToGenerateRepositoryClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a connection, object type or object to generate test classes..
        /// </summary>
        public static string SelectNodeToGenerateTestClasses {
            get {
                return ResourceManager.GetString("SelectNodeToGenerateTestClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an object type to clear the filter..
        /// </summary>
        public static string SelectObjectTypeToClearFilter {
            get {
                return ResourceManager.GetString("SelectObjectTypeToClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an object type to configure the filter..
        /// </summary>
        public static string SelectObjectTypeToConfigureFilter {
            get {
                return ResourceManager.GetString("SelectObjectTypeToConfigureFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an object type to configure mappings..
        /// </summary>
        public static string SelectObjectTypeToConfigureMappings {
            get {
                return ResourceManager.GetString("SelectObjectTypeToConfigureMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an object type to configure templates..
        /// </summary>
        public static string SelectObjectTypeToConfigureTemplates {
            get {
                return ResourceManager.GetString("SelectObjectTypeToConfigureTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a table..
        /// </summary>
        public static string SelectTableMessage {
            get {
                return ResourceManager.GetString("SelectTableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings exported successfully..
        /// </summary>
        public static string SettingsExportedSuccessfully {
            get {
                return ResourceManager.GetString("SettingsExportedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings imported successfully..
        /// </summary>
        public static string SettingsImportedSuccessfully {
            get {
                return ResourceManager.GetString("SettingsImportedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table:.
        /// </summary>
        public static string TableLabel {
            get {
                return ResourceManager.GetString("TableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure templates.
        /// </summary>
        public static string TemplateConfigTitle {
            get {
                return ResourceManager.GetString("TemplateConfigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template not found: {0}.
        /// </summary>
        public static string TemplateNotFound {
            get {
                return ResourceManager.GetString("TemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model/repository templates updated..
        /// </summary>
        public static string TemplatesUpdated {
            get {
                return ResourceManager.GetString("TemplatesUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test class generation completed. Files generated: {0}..
        /// </summary>
        public static string TestClassGenerationCompletedCount {
            get {
                return ResourceManager.GetString("TestClassGenerationCompletedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract test scenario.
        /// </summary>
        public static string TestScenarioTitle {
            get {
                return ResourceManager.GetString("TestScenarioTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error.
        /// </summary>
        public static string UnexpectedErrorTitle {
            get {
                return ResourceManager.GetString("UnexpectedErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        public static string ValidationTitle {
            get {
                return ResourceManager.GetString("ValidationTitle", resourceCulture);
            }
        }
    }
}
